// GENERATED by tools/codegen.py from sheets/*.json. Do not edit: change the sheet and regenerate.
#![allow(dead_code, clippy::all)]

/// A reference to a row in another sheet (loot table entries).
#[derive(Clone, Copy, Debug, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub enum Ref {
    Ammo(usize),
    Animations(usize),
    BuildPieces(usize),
    Camera(usize),
    Consumables(usize),
    Containers(usize),
    Controls(usize),
    ErRows(usize),
    FortniteAssets(usize),
    Harvestables(usize),
    Hud(usize),
    LootTables(usize),
    Materials(usize),
    Movement(usize),
    Pickaxe(usize),
    Rarities(usize),
    RegionTiers(usize),
    SpawnRules(usize),
    Systems(usize),
    Weapons(usize),
}

pub const AMMO_LIGHT: usize = 0;
pub const AMMO_MEDIUM: usize = 1;
pub const AMMO_HEAVY: usize = 2;
pub const AMMO_SHELLS: usize = 3;
pub const AMMO_ROCKETS: usize = 4;

/// Fortnite ammo types. Stack caps are Fortnite's inventory caps; chest_drop is how much one ammo box/chest roll gives.
#[derive(Debug)]
pub struct AmmoRow {
    /// key
    pub id: &'static str,
    /// display name
    pub name: &'static str,
    /// carry cap
    pub max: u32,
    /// amount per chest roll
    pub chest_drop: u32,
    /// amount from an ammo box
    pub box_drop: u32,
    /// @fortnite_assets row
    pub fn_icon: usize,
}

pub static AMMO: [AmmoRow; 5] = [
    AmmoRow { id: "light", name: "Light Bullets", max: 999, chest_drop: 18, box_drop: 18, fn_icon: FORTNITE_ASSETS_ICON_AMMO_LIGHT },
    AmmoRow { id: "medium", name: "Medium Bullets", max: 999, chest_drop: 10, box_drop: 10, fn_icon: FORTNITE_ASSETS_ICON_AMMO_MEDIUM },
    AmmoRow { id: "heavy", name: "Heavy Bullets", max: 999, chest_drop: 6, box_drop: 6, fn_icon: FORTNITE_ASSETS_ICON_AMMO_HEAVY },
    AmmoRow { id: "shells", name: "Shells", max: 999, chest_drop: 5, box_drop: 5, fn_icon: FORTNITE_ASSETS_ICON_AMMO_SHELLS },
    AmmoRow { id: "rockets", name: "Rockets", max: 999, chest_drop: 3, box_drop: 2, fn_icon: FORTNITE_ASSETS_ICON_AMMO_ROCKETS },
];

pub const ANIMATIONS_LOCOMOTION: usize = 0;
pub const ANIMATIONS_PICKAXE: usize = 1;
pub const ANIMATIONS_RIFLE: usize = 2;
pub const ANIMATIONS_SHOTGUN: usize = 3;
pub const ANIMATIONS_PISTOL: usize = 4;
pub const ANIMATIONS_LAUNCHER: usize = 5;
pub const ANIMATIONS_CONSUME: usize = 6;
pub const ANIMATIONS_BUILD: usize = 7;
pub const ANIMATIONS_RIDING: usize = 8;

/// Animation sets for the Fortnite outfit, played by the DLL's own skinned-mesh renderer on Fortnite's skeleton. Each row is one animation group; clips are @fortnite_assets rows.
#[derive(Debug)]
pub struct AnimationsRow {
    /// key
    pub id: &'static str,
    /// which states use it
    pub used_for: &'static str,
    /// map of state -> @fortnite_assets row
    pub clips: &'static [(&'static str, usize)],
}

pub static ANIMATIONS: [AnimationsRow; 9] = [
    AnimationsRow { id: "locomotion", used_for: "idle, run, sprint, jump, fall, land, crouch", clips: &[("idle", FORTNITE_ASSETS_ANIM_IDLE), ("run", FORTNITE_ASSETS_ANIM_JOG), ("sprint", FORTNITE_ASSETS_ANIM_SPRINT), ("jump", FORTNITE_ASSETS_ANIM_JUMP), ("fall", FORTNITE_ASSETS_ANIM_FALL), ("land", FORTNITE_ASSETS_ANIM_LAND), ("crouch_idle", FORTNITE_ASSETS_ANIM_CROUCH_IDLE), ("crouch_walk", FORTNITE_ASSETS_ANIM_CROUCH_WALK)] },
    AnimationsRow { id: "pickaxe", used_for: "harvesting tool held and swing", clips: &[("idle", FORTNITE_ASSETS_ANIM_PICKAXE_IDLE), ("swing", FORTNITE_ASSETS_ANIM_PICKAXE_SWING), ("swing2", FORTNITE_ASSETS_ANIM_PICKAXE_SWING2), ("swing3", FORTNITE_ASSETS_ANIM_PICKAXE_SWING3), ("swing4", FORTNITE_ASSETS_ANIM_PICKAXE_SWING4)] },
    AnimationsRow { id: "rifle", used_for: "AR, SMG, sniper", clips: &[("idle", FORTNITE_ASSETS_ANIM_RIFLE_IDLE), ("fire", FORTNITE_ASSETS_ANIM_RIFLE_FIRE), ("reload", FORTNITE_ASSETS_ANIM_RIFLE_RELOAD), ("ads", FORTNITE_ASSETS_ANIM_RIFLE_ADS)] },
    AnimationsRow { id: "shotgun", used_for: "pump", clips: &[("idle", FORTNITE_ASSETS_ANIM_SHOTGUN_IDLE), ("fire", FORTNITE_ASSETS_ANIM_SHOTGUN_FIRE), ("reload", FORTNITE_ASSETS_ANIM_SHOTGUN_RELOAD), ("ads", FORTNITE_ASSETS_ANIM_RIFLE_ADS)] },
    AnimationsRow { id: "pistol", used_for: "pistol", clips: &[("idle", FORTNITE_ASSETS_ANIM_PISTOL_IDLE), ("fire", FORTNITE_ASSETS_ANIM_PISTOL_FIRE), ("reload", FORTNITE_ASSETS_ANIM_PISTOL_RELOAD), ("ads", FORTNITE_ASSETS_ANIM_PISTOL_ADS)] },
    AnimationsRow { id: "launcher", used_for: "rocket launcher", clips: &[("idle", FORTNITE_ASSETS_ANIM_LAUNCHER_IDLE), ("fire", FORTNITE_ASSETS_ANIM_LAUNCHER_FIRE), ("reload", FORTNITE_ASSETS_ANIM_LAUNCHER_RELOAD), ("ads", FORTNITE_ASSETS_ANIM_RIFLE_ADS)] },
    AnimationsRow { id: "consume", used_for: "bandage, medkit, shields", clips: &[("bandage", FORTNITE_ASSETS_ANIM_BANDAGE), ("drink", FORTNITE_ASSETS_ANIM_DRINK)] },
    AnimationsRow { id: "build", used_for: "placing a piece", clips: &[("place", FORTNITE_ASSETS_ANIM_BUILD)] },
    AnimationsRow { id: "riding", used_for: "sitting on Torrent (Elden Ring drives)", clips: &[("sit", FORTNITE_ASSETS_ANIM_SIT)] },
];

pub const BUILD_PIECES_WALL: usize = 0;
pub const BUILD_PIECES_FLOOR: usize = 1;
pub const BUILD_PIECES_RAMP: usize = 2;
pub const BUILD_PIECES_CONE: usize = 3;

/// Fortnite build pieces on Fortnite's grid (a tile is 5.12 m square, a storey 3.84 m tall). The DLL draws the Fortnite mesh and owns their collision: the Fortnite movement controller, camera and your bu
#[derive(Debug)]
pub struct BuildPiecesRow {
    /// key
    pub id: &'static str,
    /// display name
    pub name: &'static str,
    /// @controls row that selects it
    pub key: usize,
    /// materials column holding its HP
    pub hp_column: &'static str,
    /// [x, y, z] extent in metres
    pub size_m: [f32; 3],
    /// tilt of the collision box (ramp: atan(3.84/5.12) = 36.87)
    pub pitch_deg: f32,
    /// placement rule: wall_edge | floor_cell | ramp_cell | cone_cell
    pub pivot: &'static str,
    /// Elden Ring asset spawned so enemies collide with it, or none (0.1: none, see about)
    pub collision_asset: &'static str,
    /// [x,y,z] native size of that asset, for scaling ([0,0,0] when none)
    pub collision_base_size_m: [f32; 3],
    /// @fortnite_assets row
    pub fn_mesh_wood: usize,
    /// @fortnite_assets row
    pub fn_mesh_stone: usize,
    /// @fortnite_assets row
    pub fn_mesh_metal: usize,
}

pub static BUILD_PIECES: [BuildPiecesRow; 4] = [
    BuildPiecesRow { id: "wall", name: "Wall", key: CONTROLS_BUILD_WALL, hp_column: "wall_hp", size_m: [5.12_f32, 0.2_f32, 3.84_f32], pitch_deg: 0.0_f32, pivot: "wall_edge", collision_asset: "none", collision_base_size_m: [0.0_f32, 0.0_f32, 0.0_f32], fn_mesh_wood: FORTNITE_ASSETS_MESH_WALL_WOOD, fn_mesh_stone: FORTNITE_ASSETS_MESH_WALL_STONE, fn_mesh_metal: FORTNITE_ASSETS_MESH_WALL_METAL },
    BuildPiecesRow { id: "floor", name: "Floor", key: CONTROLS_BUILD_FLOOR, hp_column: "floor_hp", size_m: [5.12_f32, 5.12_f32, 0.2_f32], pitch_deg: 0.0_f32, pivot: "floor_cell", collision_asset: "none", collision_base_size_m: [0.0_f32, 0.0_f32, 0.0_f32], fn_mesh_wood: FORTNITE_ASSETS_MESH_FLOOR_WOOD, fn_mesh_stone: FORTNITE_ASSETS_MESH_FLOOR_STONE, fn_mesh_metal: FORTNITE_ASSETS_MESH_FLOOR_METAL },
    BuildPiecesRow { id: "ramp", name: "Ramp", key: CONTROLS_BUILD_RAMP, hp_column: "ramp_hp", size_m: [5.12_f32, 6.4_f32, 0.2_f32], pitch_deg: 36.87_f32, pivot: "ramp_cell", collision_asset: "none", collision_base_size_m: [0.0_f32, 0.0_f32, 0.0_f32], fn_mesh_wood: FORTNITE_ASSETS_MESH_RAMP_WOOD, fn_mesh_stone: FORTNITE_ASSETS_MESH_RAMP_STONE, fn_mesh_metal: FORTNITE_ASSETS_MESH_RAMP_METAL },
    BuildPiecesRow { id: "cone", name: "Cone", key: CONTROLS_BUILD_CONE, hp_column: "floor_hp", size_m: [5.12_f32, 5.12_f32, 1.92_f32], pitch_deg: 0.0_f32, pivot: "cone_cell", collision_asset: "none", collision_base_size_m: [0.0_f32, 0.0_f32, 0.0_f32], fn_mesh_wood: FORTNITE_ASSETS_MESH_CONE_WOOD, fn_mesh_stone: FORTNITE_ASSETS_MESH_CONE_STONE, fn_mesh_metal: FORTNITE_ASSETS_MESH_CONE_METAL },
];

pub const CAMERA_FOV: usize = 0;
pub const CAMERA_BOOM_LENGTH_M: usize = 1;
pub const CAMERA_SHOULDER_OFFSET_M: usize = 2;
pub const CAMERA_ADS_BOOM_LENGTH_M: usize = 3;
pub const CAMERA_ADS_BLEND_S: usize = 4;
pub const CAMERA_PITCH_MIN_DEG: usize = 5;
pub const CAMERA_PITCH_MAX_DEG: usize = 6;
pub const CAMERA_MOUSE_SENS: usize = 7;
pub const CAMERA_COLLISION_RADIUS_M: usize = 8;

// camera: Fortnite's over-the-shoulder third-person camera, written into Elden Ring's ChrCam each frame after the game's
/// hip-fire horizontal FOV in degrees (Fortnite default
pub const CAMERA_FOV_V: f32 = 80.0_f32;
/// distance behind the character
pub const CAMERA_BOOM_LENGTH_M_V: f32 = 2.6_f32;
/// right, forward, up offset of the pivot from the head
pub const CAMERA_SHOULDER_OFFSET_M_V: [f32; 3] = [0.65_f32, 0.0_f32, 0.55_f32];
/// distance while aiming
pub const CAMERA_ADS_BOOM_LENGTH_M_V: f32 = 1.3_f32;
/// time to blend into aim
pub const CAMERA_ADS_BLEND_S_V: f32 = 0.15_f32;
/// lowest look angle
pub const CAMERA_PITCH_MIN_DEG_V: f32 = -80.0_f32;
/// highest look angle
pub const CAMERA_PITCH_MAX_DEG_V: f32 = 80.0_f32;
/// degrees per mouse count at 1.0 sensitivity
pub const CAMERA_MOUSE_SENS_V: f32 = 0.08_f32;
/// camera probe radius against walls
pub const CAMERA_COLLISION_RADIUS_M_V: f32 = 0.2_f32;

pub const CONSUMABLES_BANDAGE: usize = 0;
pub const CONSUMABLES_MEDKIT: usize = 1;
pub const CONSUMABLES_SMALL_SHIELD: usize = 2;
pub const CONSUMABLES_SHIELD_POTION: usize = 3;

/// Healing and shields. Fortnite numbers on Fortnite's 100 HP / 100 shield scale; the DLL maps 100 HP to the Tarnished's max HP (see systems:health_shield).
#[derive(Debug)]
pub struct ConsumablesRow {
    /// key
    pub id: &'static str,
    /// display name
    pub name: &'static str,
    /// health | shield
    pub restores: &'static str,
    /// points restored
    pub amount: f32,
    /// won't heal above this
    pub cap: f32,
    /// use time seconds
    pub use_s: f32,
    /// max per slot
    pub stack: u32,
    /// @fortnite_assets row
    pub fn_mesh: usize,
    /// @fortnite_assets row
    pub fn_icon: usize,
    /// @fortnite_assets row
    pub fn_use_sound: usize,
}

pub static CONSUMABLES: [ConsumablesRow; 4] = [
    ConsumablesRow { id: "bandage", name: "Bandages", restores: "health", amount: 15.0_f32, cap: 75.0_f32, use_s: 3.5_f32, stack: 15, fn_mesh: FORTNITE_ASSETS_MESH_BANDAGE, fn_icon: FORTNITE_ASSETS_ICON_BANDAGE, fn_use_sound: FORTNITE_ASSETS_SND_HEAL },
    ConsumablesRow { id: "medkit", name: "Med Kit", restores: "health", amount: 100.0_f32, cap: 100.0_f32, use_s: 10.0_f32, stack: 3, fn_mesh: FORTNITE_ASSETS_MESH_MEDKIT, fn_icon: FORTNITE_ASSETS_ICON_MEDKIT, fn_use_sound: FORTNITE_ASSETS_SND_HEAL },
    ConsumablesRow { id: "small_shield", name: "Small Shield Potion", restores: "shield", amount: 25.0_f32, cap: 50.0_f32, use_s: 2.0_f32, stack: 6, fn_mesh: FORTNITE_ASSETS_MESH_SMALL_SHIELD, fn_icon: FORTNITE_ASSETS_ICON_SMALL_SHIELD, fn_use_sound: FORTNITE_ASSETS_SND_SHIELD_DRINK },
    ConsumablesRow { id: "shield_potion", name: "Shield Potion", restores: "shield", amount: 50.0_f32, cap: 100.0_f32, use_s: 5.0_f32, stack: 3, fn_mesh: FORTNITE_ASSETS_MESH_SHIELD_POTION, fn_icon: FORTNITE_ASSETS_ICON_SHIELD_POTION, fn_use_sound: FORTNITE_ASSETS_SND_SHIELD_DRINK },
];

pub const CONTAINERS_CHEST: usize = 0;
pub const CONTAINERS_AMMO_BOX: usize = 1;

/// Fortnite loot containers placed in the Elden Ring world.
#[derive(Debug)]
pub struct ContainersRow {
    /// key
    pub id: &'static str,
    /// prompt text
    pub name: &'static str,
    /// @loot_tables row
    pub loot: usize,
    /// hold-to-search time
    pub open_s: f32,
    /// number of loot rolls
    pub rolls: u32,
    /// glow colour when unopened
    pub glow: &'static str,
    /// distance at which the chest hum plays
    pub hum_radius_m: f32,
    /// @spawn_rules row
    pub placement: usize,
    /// @fortnite_assets row
    pub fn_mesh: usize,
    /// @fortnite_assets row
    pub fn_open_sound: usize,
    /// @fortnite_assets row
    pub fn_hum_sound: usize,
    /// first version that has it
    pub release: &'static str,
}

pub static CONTAINERS: [ContainersRow; 2] = [
    ContainersRow { id: "chest", name: "Search Chest", loot: LOOT_TABLES_CHEST, open_s: 0.25_f32, rolls: 3, glow: "#FFD34D", hum_radius_m: 12.0_f32, placement: SPAWN_RULES_CHEST_RULE, fn_mesh: FORTNITE_ASSETS_MESH_CHEST, fn_open_sound: FORTNITE_ASSETS_SND_CHEST_OPEN, fn_hum_sound: FORTNITE_ASSETS_SND_CHEST_HUM, release: "0.1" },
    ContainersRow { id: "ammo_box", name: "Search Ammo Box", loot: LOOT_TABLES_AMMO_BOX, open_s: 0.25_f32, rolls: 2, glow: "#7AD1FF", hum_radius_m: 0.0_f32, placement: SPAWN_RULES_AMMO_RULE, fn_mesh: FORTNITE_ASSETS_MESH_AMMO_BOX, fn_open_sound: FORTNITE_ASSETS_SND_AMMO_BOX_OPEN, fn_hum_sound: FORTNITE_ASSETS_SND_NONE, release: "0.1" },
];

pub const CONTROLS_MOVE_FWD: usize = 0;
pub const CONTROLS_MOVE_BACK: usize = 1;
pub const CONTROLS_MOVE_LEFT: usize = 2;
pub const CONTROLS_MOVE_RIGHT: usize = 3;
pub const CONTROLS_JUMP: usize = 4;
pub const CONTROLS_SPRINT: usize = 5;
pub const CONTROLS_CROUCH: usize = 6;
pub const CONTROLS_FIRE: usize = 7;
pub const CONTROLS_AIM: usize = 8;
pub const CONTROLS_RELOAD: usize = 9;
pub const CONTROLS_INTERACT: usize = 10;
pub const CONTROLS_PICKAXE: usize = 11;
pub const CONTROLS_SLOT1: usize = 12;
pub const CONTROLS_SLOT2: usize = 13;
pub const CONTROLS_SLOT3: usize = 14;
pub const CONTROLS_SLOT4: usize = 15;
pub const CONTROLS_SLOT5: usize = 16;
pub const CONTROLS_BUILD_MODE: usize = 17;
pub const CONTROLS_BUILD_WALL: usize = 18;
pub const CONTROLS_BUILD_FLOOR: usize = 19;
pub const CONTROLS_BUILD_RAMP: usize = 20;
pub const CONTROLS_BUILD_CONE: usize = 21;
pub const CONTROLS_EDIT: usize = 22;
pub const CONTROLS_BUILD_MATERIAL: usize = 23;
pub const CONTROLS_MAP: usize = 24;
pub const CONTROLS_MENU: usize = 25;
pub const CONTROLS_FLASK: usize = 26;
pub const CONTROLS_TORRENT: usize = 27;
pub const CONTROLS_HEAL_ITEM: usize = 28;

/// Fortnite's PC default bindings. The DLL reads the keyboard and mouse itself, hides the keys it owns from Elden Ring (DirectInput state hook), and presses Elden Ring's own key for actions the game stil
#[derive(Debug)]
pub struct ControlsRow {
    /// key
    pub id: &'static str,
    /// Fortnite default key (DIK name or mouse button)
    pub key: &'static str,
    /// what it does
    pub action: &'static str,
    /// mod | er | both
    pub owner: &'static str,
    /// Elden Ring default key pressed for the player, or none
    pub er_key: &'static str,
}

pub static CONTROLS: [ControlsRow; 29] = [
    ControlsRow { id: "move_fwd", key: "W", action: "move forward", owner: "mod", er_key: "none" },
    ControlsRow { id: "move_back", key: "S", action: "move back", owner: "mod", er_key: "none" },
    ControlsRow { id: "move_left", key: "A", action: "move left", owner: "mod", er_key: "none" },
    ControlsRow { id: "move_right", key: "D", action: "move right", owner: "mod", er_key: "none" },
    ControlsRow { id: "jump", key: "SPACE", action: "jump", owner: "mod", er_key: "none" },
    ControlsRow { id: "sprint", key: "LCONTROL", action: "sprint (hold)", owner: "mod", er_key: "none" },
    ControlsRow { id: "crouch", key: "WHEELUP", action: "crouch (toggle; scroll up)", owner: "mod", er_key: "none" },
    ControlsRow { id: "fire", key: "MOUSE1", action: "fire / swing pickaxe / place build", owner: "mod", er_key: "none" },
    ControlsRow { id: "aim", key: "MOUSE2", action: "aim down sights", owner: "mod", er_key: "none" },
    ControlsRow { id: "reload", key: "C", action: "reload", owner: "mod", er_key: "none" },
    ControlsRow { id: "interact", key: "WHEELDOWN", action: "search chest, pick up, and Elden Ring interactions (graces, doors, NPCs); scroll down", owner: "both", er_key: "E" },
    ControlsRow { id: "pickaxe", key: "LSHIFT", action: "equip harvesting tool", owner: "mod", er_key: "none" },
    ControlsRow { id: "slot1", key: "1", action: "weapon slot 1", owner: "mod", er_key: "none" },
    ControlsRow { id: "slot2", key: "2", action: "weapon slot 2", owner: "mod", er_key: "none" },
    ControlsRow { id: "slot3", key: "3", action: "weapon slot 3", owner: "mod", er_key: "none" },
    ControlsRow { id: "slot4", key: "4", action: "weapon slot 4", owner: "mod", er_key: "none" },
    ControlsRow { id: "slot5", key: "5", action: "weapon slot 5", owner: "mod", er_key: "none" },
    ControlsRow { id: "build_mode", key: "NONE", action: "unbound: a build key enters build mode, a weapon or the pickaxe leaves it", owner: "mod", er_key: "none" },
    ControlsRow { id: "build_wall", key: "R", action: "select wall", owner: "mod", er_key: "none" },
    ControlsRow { id: "build_floor", key: "E", action: "select floor", owner: "mod", er_key: "none" },
    ControlsRow { id: "build_ramp", key: "Q", action: "select ramp", owner: "mod", er_key: "none" },
    ControlsRow { id: "build_cone", key: "EQUALS", action: "select cone (roof)", owner: "mod", er_key: "none" },
    ControlsRow { id: "edit", key: "F", action: "edit a build piece (not implemented yet)", owner: "mod", er_key: "none" },
    ControlsRow { id: "build_material", key: "MOUSE2", action: "cycle wood/stone/metal in build mode", owner: "mod", er_key: "none" },
    ControlsRow { id: "map", key: "M", action: "open the Elden Ring map", owner: "er", er_key: "G" },
    ControlsRow { id: "menu", key: "ESCAPE", action: "Elden Ring menu (inventory, level up at graces, system)", owner: "er", er_key: "ESCAPE" },
    ControlsRow { id: "flask", key: "H", action: "drink equipped Elden Ring flask (Crimson Tears still heal)", owner: "er", er_key: "R" },
    ControlsRow { id: "torrent", key: "B", action: "summon / dismiss Torrent (Elden Ring controls while riding)", owner: "er", er_key: "none" },
    ControlsRow { id: "heal_item", key: "NONE", action: "unbound: heals and shields sit in hotbar slots, select and fire to use", owner: "mod", er_key: "none" },
];

pub const ER_ROWS_GUN_BULLET: usize = 0;
pub const ER_ROWS_GUN_ATK: usize = 1;
pub const ER_ROWS_ROCKET_BLAST_BULLET: usize = 2;
pub const ER_ROWS_ROCKET_BLAST_ATK: usize = 3;
pub const ER_ROWS_YOU_DIED_BANNER: usize = 4;

/// Elden Ring param rows the DLL takes over in memory (nothing is written to the game's files). On boot it picks the first candidate row that exists, overwrites the listed fields, and logs the row's old 
#[derive(Debug)]
pub struct ErRowsRow {
    /// key
    pub id: &'static str,
    /// SoloParam name in fromsoftware-rs
    pub param: &'static str,
    /// row ids to try, in order
    pub candidates: &'static [u32],
    /// fields the DLL overwrites
    pub sets: &'static [&'static str],
    /// what it is for
    pub why: &'static str,
}

pub static ER_ROWS: [ErRowsRow; 5] = [
    ErRowsRow { id: "gun_bullet", param: "Bullet", candidates: &[1700, 1700000, 10170000], sets: &["atkId_Bullet", "life", "initVellocity", "maxVellocity", "hitRadius", "gravityInRange", "sfxId_Bullet", "sfxId_Hit"], why: "the projectile every Fortnite gun and the pickaxe spawns; speed/life set per shot" },
    ErRowsRow { id: "gun_atk", param: "AtkParam_Pc", candidates: &[1700, 1700000, 10170000], sets: &["atkPhys", "atkPhysCorrection", "hit0_Radius"], why: "damage of gun_bullet; atkPhys set to the held gun's damage before each shot" },
    ErRowsRow { id: "rocket_blast_bullet", param: "Bullet", candidates: &[1701, 1700001, 10170001], sets: &["atkId_Bullet", "life", "hitRadius", "sfxId_Bullet"], why: "the rocket's explosion (spawned at the impact point)" },
    ErRowsRow { id: "rocket_blast_atk", param: "AtkParam_Pc", candidates: &[1701, 1700001, 10170001], sets: &["atkPhys", "hit0_Radius"], why: "rocket explosion damage and radius" },
    ErRowsRow { id: "you_died_banner", param: "FeTextEffectParam", candidates: &[5, 50], sets: &["resId", "textId", "seId"], why: "blank YOU DIED (CS2 conversion note, verified there on 2.7.1.0) so the Fortnite eliminated screen shows instead" },
];

pub const FORTNITE_ASSETS_OUTFIT: usize = 0;
pub const FORTNITE_ASSETS_PICKAXE: usize = 1;
pub const FORTNITE_ASSETS_MESH_AR: usize = 2;
pub const FORTNITE_ASSETS_ICON_AR: usize = 3;
pub const FORTNITE_ASSETS_SND_AR_FIRE: usize = 4;
pub const FORTNITE_ASSETS_SND_AR_RELOAD: usize = 5;
pub const FORTNITE_ASSETS_MESH_PUMP: usize = 6;
pub const FORTNITE_ASSETS_ICON_PUMP: usize = 7;
pub const FORTNITE_ASSETS_SND_PUMP_FIRE: usize = 8;
pub const FORTNITE_ASSETS_SND_PUMP_RELOAD: usize = 9;
pub const FORTNITE_ASSETS_MESH_SMG: usize = 10;
pub const FORTNITE_ASSETS_ICON_SMG: usize = 11;
pub const FORTNITE_ASSETS_SND_SMG_FIRE: usize = 12;
pub const FORTNITE_ASSETS_SND_SMG_RELOAD: usize = 13;
pub const FORTNITE_ASSETS_MESH_SNIPER: usize = 14;
pub const FORTNITE_ASSETS_ICON_SNIPER: usize = 15;
pub const FORTNITE_ASSETS_SND_SNIPER_FIRE: usize = 16;
pub const FORTNITE_ASSETS_SND_SNIPER_RELOAD: usize = 17;
pub const FORTNITE_ASSETS_MESH_PISTOL: usize = 18;
pub const FORTNITE_ASSETS_ICON_PISTOL: usize = 19;
pub const FORTNITE_ASSETS_SND_PISTOL_FIRE: usize = 20;
pub const FORTNITE_ASSETS_SND_PISTOL_RELOAD: usize = 21;
pub const FORTNITE_ASSETS_MESH_ROCKET: usize = 22;
pub const FORTNITE_ASSETS_ICON_ROCKET: usize = 23;
pub const FORTNITE_ASSETS_SND_ROCKET_FIRE: usize = 24;
pub const FORTNITE_ASSETS_SND_ROCKET_RELOAD: usize = 25;
pub const FORTNITE_ASSETS_UI_RARITY_COMMON: usize = 26;
pub const FORTNITE_ASSETS_UI_RARITY_UNCOMMON: usize = 27;
pub const FORTNITE_ASSETS_UI_RARITY_RARE: usize = 28;
pub const FORTNITE_ASSETS_UI_RARITY_EPIC: usize = 29;
pub const FORTNITE_ASSETS_UI_RARITY_LEGENDARY: usize = 30;
pub const FORTNITE_ASSETS_ICON_AMMO_LIGHT: usize = 31;
pub const FORTNITE_ASSETS_ICON_AMMO_MEDIUM: usize = 32;
pub const FORTNITE_ASSETS_ICON_AMMO_HEAVY: usize = 33;
pub const FORTNITE_ASSETS_ICON_AMMO_SHELLS: usize = 34;
pub const FORTNITE_ASSETS_ICON_AMMO_ROCKETS: usize = 35;
pub const FORTNITE_ASSETS_MESH_BANDAGE: usize = 36;
pub const FORTNITE_ASSETS_ICON_BANDAGE: usize = 37;
pub const FORTNITE_ASSETS_MESH_MEDKIT: usize = 38;
pub const FORTNITE_ASSETS_ICON_MEDKIT: usize = 39;
pub const FORTNITE_ASSETS_MESH_SMALL_SHIELD: usize = 40;
pub const FORTNITE_ASSETS_ICON_SMALL_SHIELD: usize = 41;
pub const FORTNITE_ASSETS_MESH_SHIELD_POTION: usize = 42;
pub const FORTNITE_ASSETS_ICON_SHIELD_POTION: usize = 43;
pub const FORTNITE_ASSETS_SND_HEAL: usize = 44;
pub const FORTNITE_ASSETS_SND_SHIELD_DRINK: usize = 45;
pub const FORTNITE_ASSETS_ICON_WOOD: usize = 46;
pub const FORTNITE_ASSETS_TEX_BUILD_WOOD: usize = 47;
pub const FORTNITE_ASSETS_MESH_WALL_WOOD: usize = 48;
pub const FORTNITE_ASSETS_MESH_FLOOR_WOOD: usize = 49;
pub const FORTNITE_ASSETS_MESH_RAMP_WOOD: usize = 50;
pub const FORTNITE_ASSETS_ICON_STONE: usize = 51;
pub const FORTNITE_ASSETS_TEX_BUILD_STONE: usize = 52;
pub const FORTNITE_ASSETS_MESH_WALL_STONE: usize = 53;
pub const FORTNITE_ASSETS_MESH_FLOOR_STONE: usize = 54;
pub const FORTNITE_ASSETS_MESH_RAMP_STONE: usize = 55;
pub const FORTNITE_ASSETS_ICON_METAL: usize = 56;
pub const FORTNITE_ASSETS_TEX_BUILD_METAL: usize = 57;
pub const FORTNITE_ASSETS_MESH_WALL_METAL: usize = 58;
pub const FORTNITE_ASSETS_MESH_FLOOR_METAL: usize = 59;
pub const FORTNITE_ASSETS_MESH_RAMP_METAL: usize = 60;
pub const FORTNITE_ASSETS_MESH_CONE_WOOD: usize = 61;
pub const FORTNITE_ASSETS_MESH_CONE_STONE: usize = 62;
pub const FORTNITE_ASSETS_MESH_CONE_METAL: usize = 63;
pub const FORTNITE_ASSETS_MESH_CHEST: usize = 64;
pub const FORTNITE_ASSETS_SND_CHEST_OPEN: usize = 65;
pub const FORTNITE_ASSETS_SND_CHEST_HUM: usize = 66;
pub const FORTNITE_ASSETS_MESH_AMMO_BOX: usize = 67;
pub const FORTNITE_ASSETS_SND_AMMO_BOX_OPEN: usize = 68;
pub const FORTNITE_ASSETS_SND_NONE: usize = 69;
pub const FORTNITE_ASSETS_UI_HEALTH_BAR: usize = 70;
pub const FORTNITE_ASSETS_UI_SHIELD_BAR: usize = 71;
pub const FORTNITE_ASSETS_UI_SLOT_FRAME: usize = 72;
pub const FORTNITE_ASSETS_UI_BUILD_SLOTS: usize = 73;
pub const FORTNITE_ASSETS_UI_RETICLES: usize = 74;
pub const FORTNITE_ASSETS_UI_HITMARKER: usize = 75;
pub const FORTNITE_ASSETS_ICON_GOLD: usize = 76;
pub const FORTNITE_ASSETS_FONT_BURBANK: usize = 77;
pub const FORTNITE_ASSETS_ANIM_IDLE: usize = 78;
pub const FORTNITE_ASSETS_ANIM_JOG: usize = 79;
pub const FORTNITE_ASSETS_ANIM_SPRINT: usize = 80;
pub const FORTNITE_ASSETS_ANIM_JUMP: usize = 81;
pub const FORTNITE_ASSETS_ANIM_FALL: usize = 82;
pub const FORTNITE_ASSETS_ANIM_LAND: usize = 83;
pub const FORTNITE_ASSETS_ANIM_CROUCH_IDLE: usize = 84;
pub const FORTNITE_ASSETS_ANIM_CROUCH_WALK: usize = 85;
pub const FORTNITE_ASSETS_ANIM_PICKAXE_IDLE: usize = 86;
pub const FORTNITE_ASSETS_ANIM_PICKAXE_SWING: usize = 87;
pub const FORTNITE_ASSETS_ANIM_PICKAXE_SWING2: usize = 88;
pub const FORTNITE_ASSETS_ANIM_PICKAXE_SWING3: usize = 89;
pub const FORTNITE_ASSETS_ANIM_PICKAXE_SWING4: usize = 90;
pub const FORTNITE_ASSETS_ANIM_RIFLE_IDLE: usize = 91;
pub const FORTNITE_ASSETS_ANIM_RIFLE_FIRE: usize = 92;
pub const FORTNITE_ASSETS_ANIM_RIFLE_RELOAD: usize = 93;
pub const FORTNITE_ASSETS_ANIM_RIFLE_ADS: usize = 94;
pub const FORTNITE_ASSETS_ANIM_SHOTGUN_IDLE: usize = 95;
pub const FORTNITE_ASSETS_ANIM_SHOTGUN_FIRE: usize = 96;
pub const FORTNITE_ASSETS_ANIM_SHOTGUN_RELOAD: usize = 97;
pub const FORTNITE_ASSETS_ANIM_PISTOL_IDLE: usize = 98;
pub const FORTNITE_ASSETS_ANIM_PISTOL_FIRE: usize = 99;
pub const FORTNITE_ASSETS_ANIM_PISTOL_RELOAD: usize = 100;
pub const FORTNITE_ASSETS_ANIM_PISTOL_ADS: usize = 101;
pub const FORTNITE_ASSETS_ANIM_LAUNCHER_IDLE: usize = 102;
pub const FORTNITE_ASSETS_ANIM_LAUNCHER_FIRE: usize = 103;
pub const FORTNITE_ASSETS_ANIM_LAUNCHER_RELOAD: usize = 104;
pub const FORTNITE_ASSETS_ANIM_BANDAGE: usize = 105;
pub const FORTNITE_ASSETS_ANIM_DRINK: usize = 106;
pub const FORTNITE_ASSETS_ANIM_BUILD: usize = 107;
pub const FORTNITE_ASSETS_ANIM_SIT: usize = 108;
pub const FORTNITE_ASSETS_SND_PICKAXE_SWING: usize = 109;
pub const FORTNITE_ASSETS_SND_HARVEST_HIT: usize = 110;

/// Every piece of Fortnite content the mashup uses. Nothing here ships with the mod: the setup tool finds each row in the player's own Fortnite install (query = regex over package paths, '-> Prop' = foll
#[derive(Debug)]
pub struct FortniteAssetsRow {
    /// key
    pub id: &'static str,
    /// skeletal_mesh | static_mesh | anim | texture | sound | font
    pub kind: &'static str,
    /// how the extractor finds it in the install
    pub query: &'static str,
    /// file under the cache folder
    pub out: &'static str,
    /// setup fails if missing (otherwise a fallback is drawn)
    pub required: bool,
}

pub static FORTNITE_ASSETS: [FortniteAssetsRow; 111] = [
    FortniteAssetsRow { id: "outfit", kind: "skeletal_mesh", query: "outfit:{config.outfit}  (CID -> CharacterParts -> SkeletalMesh, merged)", out: "skeletal_mesh/outfit.glb", required: true },
    FortniteAssetsRow { id: "pickaxe", kind: "static_mesh", query: "pickaxe:{config.pickaxe}  (Pickaxe_ID -> WeaponDefinition -> mesh)", out: "static_mesh/pickaxe.glb", required: true },
    FortniteAssetsRow { id: "mesh_ar", kind: "static_mesh", query: "/Athena/Items/Weapons/WID_Assault_AutoHigh_Athena_R_Ore_T03$ -> WeaponMeshOverride|PickupStaticMesh|PickupSkeletalMesh", out: "static_mesh/mesh_ar.glb", required: true },
    FortniteAssetsRow { id: "icon_ar", kind: "texture", query: "/Athena/Items/Weapons/WID_Assault_AutoHigh_Athena_R_Ore_T03$ -> LargeIcon", out: "texture/icon_ar.png", required: true },
    FortniteAssetsRow { id: "snd_ar_fire", kind: "sound", query: "(?i)/Sounds/Fort_Weapons/AutoRifle/AssaultHeavy/AssaultHeavy_Fire_Close_01$", out: "sound/snd_ar_fire.wav", required: true },
    FortniteAssetsRow { id: "snd_ar_reload", kind: "sound", query: "(?i)/Sounds/Fort_Weapons/AutoRifle/AssaultHeavy/AssaultHeavy_ReloadStart_02$", out: "sound/snd_ar_reload.wav", required: true },
    FortniteAssetsRow { id: "mesh_pump", kind: "static_mesh", query: "/WID_Shotgun_Standard_Athena_UR_BB$ -> WeaponMeshOverride|PickupStaticMesh|PickupSkeletalMesh", out: "static_mesh/mesh_pump.glb", required: true },
    FortniteAssetsRow { id: "icon_pump", kind: "texture", query: "/WID_Shotgun_Standard_Athena_UR_BB$ -> LargeIcon", out: "texture/icon_pump.png", required: true },
    FortniteAssetsRow { id: "snd_pump_fire", kind: "sound", query: "(?i)/Sounds/Fort_Weapons/Shotgun/Pump/Shotgun_Pump_NewFire2_01$", out: "sound/snd_pump_fire.wav", required: true },
    FortniteAssetsRow { id: "snd_pump_reload", kind: "sound", query: "(?i)/Sounds/Fort_Weapons/Shotgun/Reload_Elements/Pump_Shotgun_InsertShell_01$", out: "sound/snd_pump_reload.wav", required: true },
    FortniteAssetsRow { id: "mesh_smg", kind: "static_mesh", query: "/Athena/Items/Weapons/WID_Pistol_AutoHeavyPDW_Athena_R_Ore_T03$ -> WeaponMeshOverride|PickupStaticMesh|PickupSkeletalMesh", out: "static_mesh/mesh_smg.glb", required: true },
    FortniteAssetsRow { id: "icon_smg", kind: "texture", query: "/Athena/Items/Weapons/WID_Pistol_AutoHeavyPDW_Athena_R_Ore_T03$ -> LargeIcon", out: "texture/icon_smg.png", required: true },
    FortniteAssetsRow { id: "snd_smg_fire", kind: "sound", query: "(?i)/Sounds/Fort_Weapons/AutoRifle/MilitarySMG/Quartz_Unvault/Military_SMG_Quartz_Fire_Close_01$", out: "sound/snd_smg_fire.wav", required: true },
    FortniteAssetsRow { id: "snd_smg_reload", kind: "sound", query: "(?i)/Sounds/Fort_Weapons/pistol/MachinePistol/SoundWaves/Machine_Pistol2_ReloadStart_01$", out: "sound/snd_smg_reload.wav", required: true },
    FortniteAssetsRow { id: "mesh_sniper", kind: "static_mesh", query: "/Athena/Items/Weapons/WID_Sniper_BoltAction_Scope_Athena_R_Ore_T03$ -> WeaponMeshOverride|PickupStaticMesh|PickupSkeletalMesh", out: "static_mesh/mesh_sniper.glb", required: true },
    FortniteAssetsRow { id: "icon_sniper", kind: "texture", query: "/Athena/Items/Weapons/WID_Sniper_BoltAction_Scope_Athena_R_Ore_T03$ -> LargeIcon", out: "texture/icon_sniper.png", required: true },
    FortniteAssetsRow { id: "snd_sniper_fire", kind: "sound", query: "(?i)/Sounds/Fort_Weapons/SniperRifles/Boltaction_HT/BoltAction_HT_Fire_Close_01$", out: "sound/snd_sniper_fire.wav", required: true },
    FortniteAssetsRow { id: "snd_sniper_reload", kind: "sound", query: "(?i)/Sounds/Fort_Weapons/SniperRifles/Boltaction_HT/Boltaction_HT_Reload_End$", out: "sound/snd_sniper_reload.wav", required: true },
    FortniteAssetsRow { id: "mesh_pistol", kind: "static_mesh", query: "/Athena/Items/Weapons/WID_Pistol_SemiAuto_Athena_R_Ore_T03$ -> WeaponMeshOverride|PickupStaticMesh|PickupSkeletalMesh", out: "static_mesh/mesh_pistol.glb", required: true },
    FortniteAssetsRow { id: "icon_pistol", kind: "texture", query: "/Athena/Items/Weapons/WID_Pistol_SemiAuto_Athena_R_Ore_T03$ -> LargeIcon", out: "texture/icon_pistol.png", required: true },
    FortniteAssetsRow { id: "snd_pistol_fire", kind: "sound", query: "(?i)/Sounds/Fort_Weapons/pistol/Modern/PistolModern_Fire_Close_01$", out: "sound/snd_pistol_fire.wav", required: true },
    FortniteAssetsRow { id: "snd_pistol_reload", kind: "sound", query: "(?i)/Sounds/Fort_Weapons/pistol/Modern/PistolModern_ReloadStart_01$", out: "sound/snd_pistol_reload.wav", required: true },
    FortniteAssetsRow { id: "mesh_rocket", kind: "static_mesh", query: "/Athena/Items/Weapons/WID_Launcher_Rocket_Athena_R_Ore_T03$ -> WeaponMeshOverride|PickupStaticMesh|PickupSkeletalMesh", out: "static_mesh/mesh_rocket.glb", required: true },
    FortniteAssetsRow { id: "icon_rocket", kind: "texture", query: "/Athena/Items/Weapons/WID_Launcher_Rocket_Athena_R_Ore_T03$ -> LargeIcon", out: "texture/icon_rocket.png", required: true },
    FortniteAssetsRow { id: "snd_rocket_fire", kind: "sound", query: "(?i)/Sounds/Fort_Weapons/Launchers/RPG/RPG_Fire_Close_01$", out: "sound/snd_rocket_fire.wav", required: true },
    FortniteAssetsRow { id: "snd_rocket_reload", kind: "sound", query: "(?i)/Sounds/Fort_Weapons/Launchers/RPG/RPG_Reload_Start_v5$", out: "sound/snd_rocket_reload.wav", required: true },
    FortniteAssetsRow { id: "ui_rarity_common", kind: "texture", query: "(?i)/UI/.*ItemRarity.*common.*|T_UI_.*Rarity.*common.*", out: "texture/ui_rarity_common.png", required: true },
    FortniteAssetsRow { id: "ui_rarity_uncommon", kind: "texture", query: "(?i)/UI/.*ItemRarity.*uncommon.*|T_UI_.*Rarity.*uncommon.*", out: "texture/ui_rarity_uncommon.png", required: true },
    FortniteAssetsRow { id: "ui_rarity_rare", kind: "texture", query: "(?i)/UI/.*ItemRarity.*rare.*|T_UI_.*Rarity.*rare.*", out: "texture/ui_rarity_rare.png", required: true },
    FortniteAssetsRow { id: "ui_rarity_epic", kind: "texture", query: "(?i)/UI/.*ItemRarity.*epic.*|T_UI_.*Rarity.*epic.*", out: "texture/ui_rarity_epic.png", required: true },
    FortniteAssetsRow { id: "ui_rarity_legendary", kind: "texture", query: "(?i)/UI/.*ItemRarity.*legendary.*|T_UI_.*Rarity.*legendary.*", out: "texture/ui_rarity_legendary.png", required: true },
    FortniteAssetsRow { id: "icon_ammo_light", kind: "texture", query: "(?i)/Items/Ammo/AthenaAmmoDataBulletsLight$ -> LargeIcon", out: "texture/icon_ammo_light.png", required: true },
    FortniteAssetsRow { id: "icon_ammo_medium", kind: "texture", query: "(?i)/Items/Ammo/AthenaAmmoDataBulletsMedium$ -> LargeIcon", out: "texture/icon_ammo_medium.png", required: true },
    FortniteAssetsRow { id: "icon_ammo_heavy", kind: "texture", query: "(?i)/Items/Ammo/AthenaAmmoDataBulletsHeavy$ -> LargeIcon", out: "texture/icon_ammo_heavy.png", required: true },
    FortniteAssetsRow { id: "icon_ammo_shells", kind: "texture", query: "(?i)/Items/Ammo/AthenaAmmoDataShells$ -> LargeIcon", out: "texture/icon_ammo_shells.png", required: true },
    FortniteAssetsRow { id: "icon_ammo_rockets", kind: "texture", query: "(?i)/Items/Ammo/AmmoDataRockets$ -> LargeIcon", out: "texture/icon_ammo_rockets.png", required: true },
    FortniteAssetsRow { id: "mesh_bandage", kind: "static_mesh", query: "/Athena/Items/Consumables/Bandage/Athena_Bandage$ -> PickupStaticMesh", out: "static_mesh/mesh_bandage.glb", required: true },
    FortniteAssetsRow { id: "icon_bandage", kind: "texture", query: "/Athena/Items/Consumables/Bandage/Athena_Bandage$ -> LargeIcon", out: "texture/icon_bandage.png", required: true },
    FortniteAssetsRow { id: "mesh_medkit", kind: "static_mesh", query: "/Athena/Items/Consumables/Medkit/Athena_Medkit$ -> PickupStaticMesh", out: "static_mesh/mesh_medkit.glb", required: true },
    FortniteAssetsRow { id: "icon_medkit", kind: "texture", query: "/Athena/Items/Consumables/Medkit/Athena_Medkit$ -> LargeIcon", out: "texture/icon_medkit.png", required: true },
    FortniteAssetsRow { id: "mesh_small_shield", kind: "static_mesh", query: "/Athena/Items/Consumables/ShieldSmall/Athena_ShieldSmall$ -> PickupStaticMesh|PickupSkeletalMesh", out: "static_mesh/mesh_small_shield.glb", required: true },
    FortniteAssetsRow { id: "icon_small_shield", kind: "texture", query: "/Athena/Items/Consumables/ShieldSmall/Athena_ShieldSmall$ -> LargeIcon", out: "texture/icon_small_shield.png", required: true },
    FortniteAssetsRow { id: "mesh_shield_potion", kind: "static_mesh", query: "/Athena/Items/Consumables/Shields/Athena_Shields$ -> PickupStaticMesh|PickupSkeletalMesh", out: "static_mesh/mesh_shield_potion.glb", required: true },
    FortniteAssetsRow { id: "icon_shield_potion", kind: "texture", query: "/Athena/Items/Consumables/Shields/Athena_Shields$ -> LargeIcon", out: "texture/icon_shield_potion.png", required: true },
    FortniteAssetsRow { id: "snd_heal", kind: "sound", query: "(?i)/Athena/Sounds/Items/Bandages/Bandage_Use$", out: "sound/snd_heal.wav", required: true },
    FortniteAssetsRow { id: "snd_shield_drink", kind: "sound", query: "(?i)/Athena/Sounds/Items/Item_Consumables_Shield_Potion_Jar_Use$", out: "sound/snd_shield_drink.wav", required: true },
    FortniteAssetsRow { id: "icon_wood", kind: "texture", query: "/Items/ResourcePickups/WoodItemData$ -> LargeIcon", out: "texture/icon_wood.png", required: true },
    FortniteAssetsRow { id: "tex_build_wood", kind: "texture", query: "/Packages/PBW/Wood/Textures/T_PBW_W1_D$", out: "texture/tex_build_wood.png", required: true },
    FortniteAssetsRow { id: "mesh_wall_wood", kind: "static_mesh", query: "/Packages/PBW/Wood/L1/PBW_W1_Solid$", out: "static_mesh/mesh_wall_wood.glb", required: true },
    FortniteAssetsRow { id: "mesh_floor_wood", kind: "static_mesh", query: "/Packages/PBW/Wood/L1/PBW_W1_Floor$", out: "static_mesh/mesh_floor_wood.glb", required: true },
    FortniteAssetsRow { id: "mesh_ramp_wood", kind: "static_mesh", query: "/Packages/PBW/Wood/L1/PBW_W1_StairW$", out: "static_mesh/mesh_ramp_wood.glb", required: true },
    FortniteAssetsRow { id: "icon_stone", kind: "texture", query: "/Items/ResourcePickups/StoneItemData$ -> LargeIcon", out: "texture/icon_stone.png", required: true },
    FortniteAssetsRow { id: "tex_build_stone", kind: "texture", query: "/Packages/PBW/Brick/Textures/T_Brick_L1A_D$", out: "texture/tex_build_stone.png", required: true },
    FortniteAssetsRow { id: "mesh_wall_stone", kind: "static_mesh", query: "/Packages/PBW/Brick/L1/PBW_B1_Solid$", out: "static_mesh/mesh_wall_stone.glb", required: true },
    FortniteAssetsRow { id: "mesh_floor_stone", kind: "static_mesh", query: "/Packages/PBW/Brick/L1/PBW_B1_Floor$", out: "static_mesh/mesh_floor_stone.glb", required: true },
    FortniteAssetsRow { id: "mesh_ramp_stone", kind: "static_mesh", query: "/Packages/PBW/Brick/L1/PBW_B1_StairW$", out: "static_mesh/mesh_ramp_stone.glb", required: true },
    FortniteAssetsRow { id: "icon_metal", kind: "texture", query: "/Items/ResourcePickups/MetalItemData$ -> LargeIcon", out: "texture/icon_metal.png", required: true },
    FortniteAssetsRow { id: "tex_build_metal", kind: "texture", query: "/Packages/PBW/Metal/Textures/T_PBW_M2_D$", out: "texture/tex_build_metal.png", required: true },
    FortniteAssetsRow { id: "mesh_wall_metal", kind: "static_mesh", query: "/Packages/PBW/Metal/L1/PBW_M1_Solid$", out: "static_mesh/mesh_wall_metal.glb", required: true },
    FortniteAssetsRow { id: "mesh_floor_metal", kind: "static_mesh", query: "/Packages/PBW/Metal/L1/PBW_M1_Floor$", out: "static_mesh/mesh_floor_metal.glb", required: true },
    FortniteAssetsRow { id: "mesh_ramp_metal", kind: "static_mesh", query: "/Packages/PBW/Metal/L1/PBW_M1_StairW$", out: "static_mesh/mesh_ramp_metal.glb", required: true },
    FortniteAssetsRow { id: "mesh_cone_wood", kind: "static_mesh", query: "/Packages/PBW/Wood/L1/PBW_W1_RoofC$", out: "static_mesh/mesh_cone_wood.glb", required: true },
    FortniteAssetsRow { id: "mesh_cone_stone", kind: "static_mesh", query: "/Packages/PBW/Brick/L1/PBW_B1_RoofC$", out: "static_mesh/mesh_cone_stone.glb", required: true },
    FortniteAssetsRow { id: "mesh_cone_metal", kind: "static_mesh", query: "/Packages/PBW/Metal/L1/PBW_M1_RoofC$", out: "static_mesh/mesh_cone_metal.glb", required: true },
    FortniteAssetsRow { id: "mesh_chest", kind: "static_mesh", query: "/Gadgets/Assets/Chest_Mark_III/Meshes/Chest_Mark_III$", out: "static_mesh/mesh_chest.glb", required: true },
    FortniteAssetsRow { id: "snd_chest_open", kind: "sound", query: "(?i)/Sounds/Foley_Loot/Containers/Treasure_Chest/treasure_chest_open_latch_01$", out: "sound/snd_chest_open.wav", required: true },
    FortniteAssetsRow { id: "snd_chest_hum", kind: "sound", query: "(?i)/Sounds/Foley_Loot/Containers/Treasure_Chest/Treasure_Chest_Ambient_Loop_01$", out: "sound/snd_chest_hum.wav", required: true },
    FortniteAssetsRow { id: "mesh_ammo_box", kind: "static_mesh", query: "/Gadgets/Assets/Ammo_Box_Mark_III/Meshes/Ammo_Box_Mark_III$", out: "static_mesh/mesh_ammo_box.glb", required: true },
    FortniteAssetsRow { id: "snd_ammo_box_open", kind: "sound", query: "(?i)/Sounds/Foley_Loot/Containers/Treasure_Chest/Treasure_Chest_Search_Start_01$", out: "sound/snd_ammo_box_open.wav", required: true },
    FortniteAssetsRow { id: "snd_none", kind: "sound", query: "(none: silence, produced by the extractor)", out: "sound/snd_none.wav", required: false },
    FortniteAssetsRow { id: "ui_health_bar", kind: "texture", query: "(?i)/Athena/HUD/Art/icon_health$", out: "texture/ui_health_bar.png", required: false },
    FortniteAssetsRow { id: "ui_shield_bar", kind: "texture", query: "(?i)/Athena/HUD/Art/icon_shield$", out: "texture/ui_shield_bar.png", required: false },
    FortniteAssetsRow { id: "ui_slot_frame", kind: "texture", query: "(?i)/UI/.*QuickBar.*Slot", out: "texture/ui_slot_frame.png", required: false },
    FortniteAssetsRow { id: "ui_build_slots", kind: "texture", query: "(?i)/UI/Fort_Quickbar/Icon_Building_(Wall|Floor|Stair)$", out: "texture/ui_build_slots.png", required: false },
    FortniteAssetsRow { id: "ui_reticles", kind: "texture", query: "(?i)/UI/.*Reticle", out: "texture/ui_reticles.png", required: false },
    FortniteAssetsRow { id: "ui_hitmarker", kind: "texture", query: "(?i)/Athena/HUD/reticles/Weapons/AthenaHUD_HitMarker$", out: "texture/ui_hitmarker.png", required: false },
    FortniteAssetsRow { id: "icon_gold", kind: "texture", query: "(?i)/UI/.*Gold.?Bar.*Icon", out: "texture/icon_gold.png", required: false },
    FortniteAssetsRow { id: "font_burbank", kind: "font", query: "(?i)/FortUILibrary/Content/Fonts/BurbankBigCondensed-Black$", out: "font/font_burbank.ttf", required: true },
    FortniteAssetsRow { id: "anim_idle", kind: "anim", query: "(?i)/Animation/Game/MainPlayer/Locomotion/Medium/Male/Idle/NoWep_Stand_Idle_Loop$  (AnimSequence on the Fortnite player skeleton, male medium)", out: "anim/anim_idle.psa", required: true },
    FortniteAssetsRow { id: "anim_jog", kind: "anim", query: "(?i)/Animation/Game/MainPlayer/Locomotion/Medium/Male/Jog/NoWeapon/M_Jog_NoWep_N_NoAdditive$  (AnimSequence on the Fortnite player skeleton, male medium; full pose, not an additive layer)", out: "anim/anim_jog.psa", required: true },
    FortniteAssetsRow { id: "anim_sprint", kind: "anim", query: "(?i)/Animation/Game/MainPlayer/Locomotion/Medium/Male/Sprint/Sprint_Default$  (AnimSequence on the Fortnite player skeleton, male medium)", out: "anim/anim_sprint.psa", required: true },
    FortniteAssetsRow { id: "anim_jump", kind: "anim", query: "(?i)/Animation/Game/MainPlayer/Locomotion/Medium/Male/Falling/JumpToFalling$  (AnimSequence on the Fortnite player skeleton, male medium; full pose, not an additive layer)", out: "anim/anim_jump.psa", required: true },
    FortniteAssetsRow { id: "anim_fall", kind: "anim", query: "(?i)/Animation/Game/MainPlayer/Locomotion/Medium/Male/InAir/NoWep_InAir_Fall_Loop_Lvl2$  (AnimSequence on the Fortnite player skeleton, male medium; full pose, not an additive layer)", out: "anim/anim_fall.psa", required: true },
    FortniteAssetsRow { id: "anim_land", kind: "anim", query: "(?i)/Animation/Game/MainPlayer/Locomotion/Medium/Male/Jump/NoWep/JumpLand_NoWep_CMM_Additive$  (AnimSequence on the Fortnite player skeleton, male medium)", out: "anim/anim_land.psa", required: true },
    FortniteAssetsRow { id: "anim_crouch_idle", kind: "anim", query: "(?i)/Animation/Game/MainPlayer/Poses/Medium/Male/StaminaHawaii/Stamina_Hawaii_Crouch_Idle_CMM$  (AnimSequence on the Fortnite player skeleton, male medium)", out: "anim/anim_crouch_idle.psa", required: true },
    FortniteAssetsRow { id: "anim_crouch_walk", kind: "anim", query: "(?i)/Animation/Game/MainPlayer/Locomotion/Medium/Male/Crouch/NoWeapon/Crouch_NoWeapon_N_NoAdditive$  (AnimSequence on the Fortnite player skeleton, male medium)", out: "anim/anim_crouch_walk.psa", required: true },
    FortniteAssetsRow { id: "anim_pickaxe_idle", kind: "anim", query: "(?i)/Animation/Game/MainPlayer/Combat/Melee/OneHanded/.*/PandaSpeak_Add_Pickaxe_IdlePose_CMM$  (AnimSequence on the Fortnite player skeleton, male medium)", out: "anim/anim_pickaxe_idle.psa", required: true },
    FortniteAssetsRow { id: "anim_pickaxe_swing", kind: "anim", query: "(?i)/Animation/Game/MainPlayer/Combat/Melee/OneHanded/CAS/CAS_Pickaxe_Harvesting_Swing1_CMM$  (AnimSequence on the Fortnite player skeleton, male medium)", out: "anim/anim_pickaxe_swing.psa", required: true },
    FortniteAssetsRow { id: "anim_pickaxe_swing2", kind: "anim", query: "(?i)/Animation/Game/MainPlayer/Combat/Melee/OneHanded/CAS/CAS_Pickaxe_Harvesting_Swing2_CMM$  (AnimSequence on the Fortnite player skeleton, male medium; the default one-handed pickaxe set, played in turn)", out: "anim/anim_pickaxe_swing2.psa", required: true },
    FortniteAssetsRow { id: "anim_pickaxe_swing3", kind: "anim", query: "(?i)/Animation/Game/MainPlayer/Combat/Melee/OneHanded/CAS/CAS_Pickaxe_Harvesting_Swing3_CMM$  (AnimSequence on the Fortnite player skeleton, male medium; the default one-handed pickaxe set, played in turn)", out: "anim/anim_pickaxe_swing3.psa", required: true },
    FortniteAssetsRow { id: "anim_pickaxe_swing4", kind: "anim", query: "(?i)/Animation/Game/MainPlayer/Combat/Melee/OneHanded/CAS/CAS_Pickaxe_Harvesting_Swing4_CMM$  (AnimSequence on the Fortnite player skeleton, male medium; the default one-handed pickaxe set, played in turn)", out: "anim/anim_pickaxe_swing4.psa", required: true },
    FortniteAssetsRow { id: "anim_rifle_idle", kind: "anim", query: "(?i)/Animation/Game/MainPlayer/Locomotion/Medium/Male/Jog/AssaultRifle_HipNonTargeted/M_Jog_AssaultRifle_N_Core$  (full-pose 'Core' stance; the Idle/IdleNoise/Patrol clips are additive layers)", out: "anim/anim_rifle_idle.psa", required: true },
    FortniteAssetsRow { id: "anim_rifle_fire", kind: "anim", query: "(?i)/Animation/Game/MainPlayer/Combat/Guns/AssaultRifle/AssaultRifle_Fire_CH5$  (AnimSequence on the Fortnite player skeleton, male medium)", out: "anim/anim_rifle_fire.psa", required: true },
    FortniteAssetsRow { id: "anim_rifle_reload", kind: "anim", query: "(?i)/Animation/Game/MainPlayer/Combat/Guns/AssaultRifle/AssaultRifle_FCBA_Reload_CMM$  (AnimSequence on the Fortnite player skeleton, male medium)", out: "anim/anim_rifle_reload.psa", required: true },
    FortniteAssetsRow { id: "anim_rifle_ads", kind: "anim", query: "(?i)/Animation/Game/MainPlayer/Locomotion/Medium/Male/Idle/Idle_Noise_AR_Downsights$  (AnimSequence on the Fortnite player skeleton, male medium)", out: "anim/anim_rifle_ads.psa", required: true },
    FortniteAssetsRow { id: "anim_shotgun_idle", kind: "anim", query: "(?i)/Animation/Game/MainPlayer/Locomotion/Medium/Male/Jog/AssaultRifle_HipNonTargeted/M_Jog_AssaultRifle_N_Core$  (full-pose 'Core' stance; the Idle/IdleNoise/Patrol clips are additive layers)", out: "anim/anim_shotgun_idle.psa", required: true },
    FortniteAssetsRow { id: "anim_shotgun_fire", kind: "anim", query: "(?i)/Animation/Game/MainPlayer/Combat/Guns/Shotgun/Shotgun_Rifle_PABF_Fire_CMM$  (AnimSequence on the Fortnite player skeleton, male medium)", out: "anim/anim_shotgun_fire.psa", required: true },
    FortniteAssetsRow { id: "anim_shotgun_reload", kind: "anim", query: "(?i)/Animation/Game/MainPlayer/Combat/Guns/Shotgun/Shotgun_Rifle_PABF_Reload_Loop_CMM$  (AnimSequence on the Fortnite player skeleton, male medium)", out: "anim/anim_shotgun_reload.psa", required: true },
    FortniteAssetsRow { id: "anim_pistol_idle", kind: "anim", query: "(?i)/Animation/Game/MainPlayer/Locomotion/Medium/Male/Jog/PistolHF/M_Jog_PistolDS_N_Core$  (full-pose 'Core' stance; the Idle/IdleNoise/Patrol clips are additive layers)", out: "anim/anim_pistol_idle.psa", required: true },
    FortniteAssetsRow { id: "anim_pistol_fire", kind: "anim", query: "(?i)/Animation/Game/MainPlayer/Combat/Guns/pistol/Pistol_FC_SA_Fire_CMM$  (AnimSequence on the Fortnite player skeleton, male medium)", out: "anim/anim_pistol_fire.psa", required: true },
    FortniteAssetsRow { id: "anim_pistol_reload", kind: "anim", query: "(?i)/Animation/Game/MainPlayer/Combat/Guns/pistol/Pistol_FC_SA_Reload_CMM$  (AnimSequence on the Fortnite player skeleton, male medium)", out: "anim/anim_pistol_reload.psa", required: true },
    FortniteAssetsRow { id: "anim_pistol_ads", kind: "anim", query: "(?i)/Animation/Game/MainPlayer/Combat/Guns/CowboyPistol/CowboyPistol_DownSights_Fire_CMM$  (AnimSequence on the Fortnite player skeleton, male medium)", out: "anim/anim_pistol_ads.psa", required: true },
    FortniteAssetsRow { id: "anim_launcher_idle", kind: "anim", query: "(?i)/Animation/Game/MainPlayer/Locomotion/Medium/Male/Idle/(.*/)?GrenadeLauncher_Idle_Patrol_Pose$  (AnimSequence on the Fortnite player skeleton, male medium)", out: "anim/anim_launcher_idle.psa", required: true },
    FortniteAssetsRow { id: "anim_launcher_fire", kind: "anim", query: "(?i)/Animation/Game/MainPlayer/Combat/Guns/Launcher/Launcher_Fire$  (AnimSequence on the Fortnite player skeleton, male medium)", out: "anim/anim_launcher_fire.psa", required: true },
    FortniteAssetsRow { id: "anim_launcher_reload", kind: "anim", query: "(?i)/Animation/Game/MainPlayer/Combat/Guns/Launcher/Launcher_Reload_CMM$  (AnimSequence on the Fortnite player skeleton, male medium)", out: "anim/anim_launcher_reload.psa", required: true },
    FortniteAssetsRow { id: "anim_bandage", kind: "anim", query: "(?i)/Animation/Game/MainPlayer/Reacts/Healing/Bandages/WrapBandages_Athena_Into$  (AnimSequence on the Fortnite player skeleton, male medium)", out: "anim/anim_bandage.psa", required: true },
    FortniteAssetsRow { id: "anim_drink", kind: "anim", query: "(?i)/Animation/Game/MainPlayer/Reacts/Healing/Drinking_30f$  (AnimSequence on the Fortnite player skeleton, male medium)", out: "anim/anim_drink.psa", required: true },
    FortniteAssetsRow { id: "anim_build", kind: "anim", query: "(?i)/Animation/Game/MainPlayer/Building/Blueprint_Equip$  (AnimSequence on the Fortnite player skeleton, male medium)", out: "anim/anim_build.psa", required: true },
    FortniteAssetsRow { id: "anim_sit", kind: "anim", query: "(?i)/Animation/Game/MainPlayer/Vehicles/ATV/ATV_Passenger_Idle$  (AnimSequence on the Fortnite player skeleton, male medium)", out: "anim/anim_sit.psa", required: true },
    FortniteAssetsRow { id: "snd_pickaxe_swing", kind: "sound", query: "(?i)/Athena/Sounds/Weapons/PickAxes/MarkIIIMale/Pickaxe_MarkIIIMale_Swing_01$", out: "sound/snd_pickaxe_swing.wav", required: false },
    FortniteAssetsRow { id: "snd_harvest_hit", kind: "sound", query: "(?i)/Athena/Sounds/Weapons/PickAxe_CQC_Impact_01$", out: "sound/snd_harvest_hit.wav", required: false },
];

pub const HARVESTABLES_TREES: usize = 0;
pub const HARVESTABLES_WOODEN_PROPS: usize = 1;
pub const HARVESTABLES_ROCKS: usize = 2;
pub const HARVESTABLES_RUINS: usize = 3;
pub const HARVESTABLES_METAL_PROPS: usize = 4;

/// What the pickaxe harvests. The DLL ray-casts the swing against the map; the hit asset's name (AEG id) picks the row by prefix. Fortnite yields per hit; hitting the weak point (critical) doubles it.
#[derive(Debug)]
pub struct HarvestablesRow {
    /// key
    pub id: &'static str,
    /// AEG name prefixes or map-collision material that count
    pub matches: &'static [&'static str],
    /// @materials row
    pub material: usize,
    /// material per swing
    pub per_hit: u32,
    /// material per weak-point swing
    pub crit_per_hit: u32,
    /// swings before it stops yielding (0 = endless, used for terrain)
    pub hits_to_break: u32,
    /// seconds before it yields again
    pub respawn_s: f32,
}

pub static HARVESTABLES: [HarvestablesRow; 5] = [
    HarvestablesRow { id: "trees", matches: &["AEG463", "AEG801", "AEG802", "AEG803"], material: MATERIALS_WOOD, per_hit: 7, crit_per_hit: 14, hits_to_break: 10, respawn_s: 600.0_f32 },
    HarvestablesRow { id: "wooden_props", matches: &["AEG001", "AEG002", "AEG003"], material: MATERIALS_WOOD, per_hit: 5, crit_per_hit: 10, hits_to_break: 4, respawn_s: 600.0_f32 },
    HarvestablesRow { id: "rocks", matches: &["AEG220", "AEG221", "AEG222", "material:rock"], material: MATERIALS_STONE, per_hit: 6, crit_per_hit: 12, hits_to_break: 12, respawn_s: 600.0_f32 },
    HarvestablesRow { id: "ruins", matches: &["AEG030", "AEG031", "material:stone_brick"], material: MATERIALS_STONE, per_hit: 5, crit_per_hit: 10, hits_to_break: 0, respawn_s: 0.0_f32 },
    HarvestablesRow { id: "metal_props", matches: &["AEG027", "AEG099_6", "material:metal"], material: MATERIALS_METAL, per_hit: 4, crit_per_hit: 8, hits_to_break: 8, respawn_s: 600.0_f32 },
];

pub const HUD_HEALTH_BAR: usize = 0;
pub const HUD_SHIELD_BAR: usize = 1;
pub const HUD_HOTBAR: usize = 2;
pub const HUD_AMMO_COUNTER: usize = 3;
pub const HUD_MATERIALS: usize = 4;
pub const HUD_BUILD_BAR: usize = 5;
pub const HUD_CROSSHAIR: usize = 6;
pub const HUD_HIT_MARKER: usize = 7;
pub const HUD_DAMAGE_NUMBERS: usize = 8;
pub const HUD_PICKUP_PROMPT: usize = 9;
pub const HUD_CONSUMABLE_SLOT: usize = 10;
pub const HUD_RUNES: usize = 11;
pub const HUD_BOSS_BAR: usize = 12;
pub const HUD_USE_PROGRESS: usize = 13;

/// The Fortnite HUD, drawn by the DLL with ImGui over Elden Ring's frame (Elden Ring's own HUD is hidden). Positions are fractions of the screen (0-1) from the top-left, sized for 16:9, matching Fortnite
#[derive(Debug)]
pub struct HudRow {
    /// key
    pub id: &'static str,
    /// [x, y] anchor, screen fraction
    pub pos: [f32; 2],
    /// [w, h] screen fraction
    pub size: [f32; 2],
    /// what it shows
    pub source: &'static str,
    /// @fortnite_assets row (or none)
    pub art: Option<usize>,
    /// always | combat | build | when_relevant
    pub visible: &'static str,
}

pub static HUD: [HudRow; 14] = [
    HudRow { id: "health_bar", pos: [0.035_f32, 0.885_f32], size: [0.2_f32, 0.018_f32], source: "health 0-100 (Elden Ring HP scaled)", art: Some(FORTNITE_ASSETS_UI_HEALTH_BAR), visible: "always" },
    HudRow { id: "shield_bar", pos: [0.035_f32, 0.86_f32], size: [0.2_f32, 0.018_f32], source: "shield 0-100", art: Some(FORTNITE_ASSETS_UI_SHIELD_BAR), visible: "always" },
    HudRow { id: "hotbar", pos: [0.62_f32, 0.86_f32], size: [0.33_f32, 0.09_f32], source: "pickaxe + 5 weapon slots, rarity backgrounds, selected slot", art: Some(FORTNITE_ASSETS_UI_SLOT_FRAME), visible: "combat" },
    HudRow { id: "ammo_counter", pos: [0.62_f32, 0.825_f32], size: [0.12_f32, 0.03_f32], source: "mag / reserve of held gun", art: None, visible: "combat" },
    HudRow { id: "materials", pos: [0.9_f32, 0.62_f32], size: [0.08_f32, 0.16_f32], source: "wood, stone, metal counts", art: Some(FORTNITE_ASSETS_ICON_WOOD), visible: "always" },
    HudRow { id: "build_bar", pos: [0.62_f32, 0.86_f32], size: [0.33_f32, 0.09_f32], source: "wall / floor / ramp slots and their cost", art: Some(FORTNITE_ASSETS_UI_BUILD_SLOTS), visible: "build" },
    HudRow { id: "crosshair", pos: [0.5_f32, 0.5_f32], size: [0.03_f32, 0.053_f32], source: "per-class reticle with live bloom", art: Some(FORTNITE_ASSETS_UI_RETICLES), visible: "combat" },
    HudRow { id: "hit_marker", pos: [0.5_f32, 0.5_f32], size: [0.03_f32, 0.053_f32], source: "hit/headshot marker on hit", art: Some(FORTNITE_ASSETS_UI_HITMARKER), visible: "when_relevant" },
    HudRow { id: "damage_numbers", pos: [0.5_f32, 0.5_f32], size: [0.0_f32, 0.0_f32], source: "floating damage numbers at the hit point (white body, yellow head, blue shield)", art: None, visible: "when_relevant" },
    HudRow { id: "pickup_prompt", pos: [0.5_f32, 0.62_f32], size: [0.2_f32, 0.06_f32], source: "E Search / E Pick up name + rarity", art: None, visible: "when_relevant" },
    HudRow { id: "consumable_slot", pos: [0.535_f32, 0.86_f32], size: [0.07_f32, 0.09_f32], source: "selected heal item and count; Crimson flask count", art: None, visible: "combat" },
    HudRow { id: "runes", pos: [0.88_f32, 0.95_f32], size: [0.1_f32, 0.03_f32], source: "Elden Ring runes held (as Fortnite gold bars style counter)", art: Some(FORTNITE_ASSETS_ICON_GOLD), visible: "always" },
    HudRow { id: "boss_bar", pos: [0.25_f32, 0.08_f32], size: [0.5_f32, 0.02_f32], source: "boss name and HP from Elden Ring's boss bar data, restyled", art: None, visible: "when_relevant" },
    HudRow { id: "use_progress", pos: [0.5_f32, 0.58_f32], size: [0.12_f32, 0.012_f32], source: "heal/shield use timer, reload timer, chest search", art: None, visible: "when_relevant" },
];

pub const LOOT_TABLES_CHEST: usize = 0;
pub const LOOT_TABLES_AMMO_BOX: usize = 1;

/// What a container roll gives. Each roll picks one entry by weight; a weapon also gets a rarity from region_tiers.rarity_weights and its own ammo (one mag's worth).
#[derive(Debug)]
pub struct LootTablesRow {
    /// key
    pub id: &'static str,
    /// list of [@ref, weight, count]; count 0 = per-row default (ammo.chest_drop)
    pub entries: &'static [(Ref, f32, u32)],
}

pub static LOOT_TABLES: [LootTablesRow; 2] = [
    LootTablesRow { id: "chest", entries: &[(Ref::Weapons(WEAPONS_AR), 18.0_f32, 1), (Ref::Weapons(WEAPONS_PUMP), 16.0_f32, 1), (Ref::Weapons(WEAPONS_SMG), 14.0_f32, 1), (Ref::Weapons(WEAPONS_SNIPER), 6.0_f32, 1), (Ref::Weapons(WEAPONS_PISTOL), 12.0_f32, 1), (Ref::Weapons(WEAPONS_ROCKET), 3.0_f32, 1), (Ref::Consumables(CONSUMABLES_BANDAGE), 8.0_f32, 5), (Ref::Consumables(CONSUMABLES_MEDKIT), 4.0_f32, 1), (Ref::Consumables(CONSUMABLES_SMALL_SHIELD), 8.0_f32, 3), (Ref::Consumables(CONSUMABLES_SHIELD_POTION), 5.0_f32, 1), (Ref::Materials(MATERIALS_WOOD), 6.0_f32, 30), (Ref::Materials(MATERIALS_STONE), 4.0_f32, 30), (Ref::Materials(MATERIALS_METAL), 3.0_f32, 30)] },
    LootTablesRow { id: "ammo_box", entries: &[(Ref::Ammo(AMMO_LIGHT), 30.0_f32, 0), (Ref::Ammo(AMMO_MEDIUM), 30.0_f32, 0), (Ref::Ammo(AMMO_HEAVY), 12.0_f32, 0), (Ref::Ammo(AMMO_SHELLS), 20.0_f32, 0), (Ref::Ammo(AMMO_ROCKETS), 4.0_f32, 0)] },
];

pub const MATERIALS_WOOD: usize = 0;
pub const MATERIALS_STONE: usize = 1;
pub const MATERIALS_METAL: usize = 2;

/// Fortnite building materials. HP values are Fortnite's max wall HP per material; build_s is how long a piece takes to reach full HP.
#[derive(Debug)]
pub struct MaterialsRow {
    /// key
    pub id: &'static str,
    /// display name
    pub name: &'static str,
    /// carry cap
    pub max: u32,
    /// cost per build piece
    pub piece_cost: u32,
    /// max HP of a wall
    pub wall_hp: u32,
    /// max HP of a floor
    pub floor_hp: u32,
    /// max HP of a ramp
    pub ramp_hp: u32,
    /// HP fraction when placed
    pub start_hp_frac: f32,
    /// seconds to reach full HP
    pub build_s: f32,
    /// @fortnite_assets row
    pub fn_icon: usize,
    /// @fortnite_assets row: build-piece texture set
    pub fn_material_tex: usize,
}

pub static MATERIALS: [MaterialsRow; 3] = [
    MaterialsRow { id: "wood", name: "Wood", max: 999, piece_cost: 10, wall_hp: 150, floor_hp: 140, ramp_hp: 140, start_hp_frac: 0.6_f32, build_s: 5.0_f32, fn_icon: FORTNITE_ASSETS_ICON_WOOD, fn_material_tex: FORTNITE_ASSETS_TEX_BUILD_WOOD },
    MaterialsRow { id: "stone", name: "Stone", max: 999, piece_cost: 10, wall_hp: 300, floor_hp: 280, ramp_hp: 280, start_hp_frac: 0.25_f32, build_s: 12.0_f32, fn_icon: FORTNITE_ASSETS_ICON_STONE, fn_material_tex: FORTNITE_ASSETS_TEX_BUILD_STONE },
    MaterialsRow { id: "metal", name: "Metal", max: 999, piece_cost: 10, wall_hp: 500, floor_hp: 460, ramp_hp: 460, start_hp_frac: 0.2_f32, build_s: 20.0_f32, fn_icon: FORTNITE_ASSETS_ICON_METAL, fn_material_tex: FORTNITE_ASSETS_TEX_BUILD_METAL },
];

pub const MOVEMENT_RUN_SPEED: usize = 0;
pub const MOVEMENT_SPRINT_SPEED: usize = 1;
pub const MOVEMENT_CROUCH_SPEED: usize = 2;
pub const MOVEMENT_ADS_SPEED_MULT: usize = 3;
pub const MOVEMENT_BACKPEDAL_MULT: usize = 4;
pub const MOVEMENT_ACCEL: usize = 5;
pub const MOVEMENT_AIR_CONTROL: usize = 6;
pub const MOVEMENT_JUMP_VELOCITY: usize = 7;
pub const MOVEMENT_GRAVITY: usize = 8;
pub const MOVEMENT_TERMINAL_VELOCITY: usize = 9;
pub const MOVEMENT_STEP_HEIGHT: usize = 10;
pub const MOVEMENT_MAX_SLOPE_DEG: usize = 11;
pub const MOVEMENT_CAPSULE_RADIUS: usize = 12;
pub const MOVEMENT_CAPSULE_HEIGHT: usize = 13;
pub const MOVEMENT_FALL_DAMAGE_START: usize = 14;
pub const MOVEMENT_FALL_DAMAGE_PER_M: usize = 15;
pub const MOVEMENT_FALL_DEATH: usize = 16;
pub const MOVEMENT_SLIDE_SPEED: usize = 17;
pub const MOVEMENT_MANTLE_HEIGHT: usize = 18;

// movement: The Fortnite movement controller. The DLL moves the Tarnished kinematically (Havok ray casts against Elden Rin
/// default forward speed (Fortnite runs by default) (m/s
pub const MOVEMENT_RUN_SPEED_V: f32 = 4.05_f32;
/// speed while sprint is held (m/s
pub const MOVEMENT_SPRINT_SPEED_V: f32 = 5.6_f32;
/// crouch walk speed (m/s
pub const MOVEMENT_CROUCH_SPEED_V: f32 = 2.6_f32;
/// movement multiplier while aiming (x
pub const MOVEMENT_ADS_SPEED_MULT_V: f32 = 0.65_f32;
/// multiplier moving backwards (x
pub const MOVEMENT_BACKPEDAL_MULT_V: f32 = 0.85_f32;
/// ground acceleration (m/s2
pub const MOVEMENT_ACCEL_V: f32 = 30.0_f32;
/// fraction of ground acceleration in the air (x
pub const MOVEMENT_AIR_CONTROL_V: f32 = 0.35_f32;
/// upward speed at take-off (m/s
pub const MOVEMENT_JUMP_VELOCITY_V: f32 = 5.6_f32;
/// falling acceleration (Fortnite's floaty-then-fast arc) (m/s2
pub const MOVEMENT_GRAVITY_V: f32 = 15.7_f32;
/// max fall speed (m/s
pub const MOVEMENT_TERMINAL_VELOCITY_V: f32 = 40.0_f32;
/// max ledge walked up without jumping (m
pub const MOVEMENT_STEP_HEIGHT_V: f32 = 0.45_f32;
/// steepest walkable slope (deg
pub const MOVEMENT_MAX_SLOPE_DEG_V: f32 = 50.0_f32;
/// collision radius (m
pub const MOVEMENT_CAPSULE_RADIUS_V: f32 = 0.38_f32;
/// collision height (m
pub const MOVEMENT_CAPSULE_HEIGHT_V: f32 = 1.8_f32;
/// fall height before damage (about three Fortnite storeys) (m
pub const MOVEMENT_FALL_DAMAGE_START_V: f32 = 11.5_f32;
/// Fortnite HP lost per metre above the threshold (hp/m
pub const MOVEMENT_FALL_DAMAGE_PER_M_V: f32 = 4.0_f32;
/// fall height that always kills (m
pub const MOVEMENT_FALL_DEATH_V: f32 = 40.0_f32;
/// (0.2) slide entry speed (m/s
pub const MOVEMENT_SLIDE_SPEED_V: f32 = 7.5_f32;
/// (0.2) highest ledge mantled (m
pub const MOVEMENT_MANTLE_HEIGHT_V: f32 = 2.2_f32;

pub const PICKAXE_DEFAULT: usize = 0;

/// The harvesting tool (Fortnite's pickaxe). It harvests materials (harvestables) and also hits enemies, scaled by region tier like the guns.
#[derive(Debug)]
pub struct PickaxeRow {
    /// key
    pub id: &'static str,
    /// Fortnite damage per swing
    pub damage: f32,
    /// seconds between swings
    pub swing_s: f32,
    /// how far it reaches
    pub reach_m: f32,
    /// @fortnite_assets row
    pub fn_mesh: usize,
    /// @fortnite_assets row
    pub fn_swing_sound: usize,
    /// @fortnite_assets row
    pub fn_hit_sound: usize,
    /// @animations row
    pub anim_set: usize,
}

pub static PICKAXE: [PickaxeRow; 1] = [
    PickaxeRow { id: "default", damage: 20.0_f32, swing_s: 0.6_f32, reach_m: 2.2_f32, fn_mesh: FORTNITE_ASSETS_PICKAXE, fn_swing_sound: FORTNITE_ASSETS_SND_PICKAXE_SWING, fn_hit_sound: FORTNITE_ASSETS_SND_HARVEST_HIT, anim_set: ANIMATIONS_PICKAXE },
];

pub const RARITIES_COMMON: usize = 0;
pub const RARITIES_UNCOMMON: usize = 1;
pub const RARITIES_RARE: usize = 2;
pub const RARITIES_EPIC: usize = 3;
pub const RARITIES_LEGENDARY: usize = 4;

/// Fortnite's five loot rarities. Colours are Fortnite's HUD rarity colours.
#[derive(Debug)]
pub struct RaritiesRow {
    /// key
    pub id: &'static str,
    /// display name
    pub name: &'static str,
    /// 0-4, index into weapons.damage/reload_s
    pub index: u32,
    /// HUD hex colour
    pub color: &'static str,
    /// pickup/chest glow hex colour
    pub glow: &'static str,
    /// @fortnite_assets row for the hotbar slot background of this rarity
    pub fn_slot_bg: usize,
}

pub static RARITIES: [RaritiesRow; 5] = [
    RaritiesRow { id: "common", name: "Common", index: 0, color: "#B1B1B1", glow: "#C8C8C8", fn_slot_bg: FORTNITE_ASSETS_UI_RARITY_COMMON },
    RaritiesRow { id: "uncommon", name: "Uncommon", index: 1, color: "#5BFD00", glow: "#69BB1E", fn_slot_bg: FORTNITE_ASSETS_UI_RARITY_UNCOMMON },
    RaritiesRow { id: "rare", name: "Rare", index: 2, color: "#00FFF6", glow: "#2CC1FF", fn_slot_bg: FORTNITE_ASSETS_UI_RARITY_RARE },
    RaritiesRow { id: "epic", name: "Epic", index: 3, color: "#D505FF", glow: "#B238FF", fn_slot_bg: FORTNITE_ASSETS_UI_RARITY_EPIC },
    RaritiesRow { id: "legendary", name: "Legendary", index: 4, color: "#F68B20", glow: "#E9A23C", fn_slot_bg: FORTNITE_ASSETS_UI_RARITY_LEGENDARY },
];

pub const REGION_TIERS_T1: usize = 0;
pub const REGION_TIERS_T2: usize = 1;
pub const REGION_TIERS_T3: usize = 2;
pub const REGION_TIERS_T4: usize = 3;
pub const REGION_TIERS_T5: usize = 4;
pub const REGION_TIERS_T6: usize = 5;

/// How loot scales through the Lands Between so Fortnite guns keep up with Elden Ring's enemies. A gun's Elden Ring damage = weapons.damage[rarity] x damage_mult of the tier it was found in. Tier is pick
#[derive(Debug)]
pub struct RegionTiersRow {
    /// key
    pub id: &'static str,
    /// where
    pub name: &'static str,
    /// map ids in this tier: mAA or mAA_BB (legacy dungeons/underground), or m60_X0-X1_Z0-Z1 (open-world tile ranges); first match wins
    pub map_areas: &'static [&'static str],
    /// gun damage multiplier
    pub damage_mult: f32,
    /// 5 weights
    pub rarity_weights: [f32; 5],
    /// typical field-enemy HP there (design note, for balance)
    pub enemy_hp_hint: f32,
}

pub static REGION_TIERS: [RegionTiersRow; 6] = [
    RegionTiersRow { id: "t1", name: "Limgrave, Weeping Peninsula, Stormveil", map_areas: &["m10", "m18", "m30_00", "m31_00", "m31_03", "m31_15", "m31_17", "m31_18", "m60_40-46_32-41"], damage_mult: 1.0_f32, rarity_weights: [50.0_f32, 30.0_f32, 15.0_f32, 4.0_f32, 1.0_f32], enemy_hp_hint: 150.0_f32 },
    RegionTiersRow { id: "t2", name: "Liurnia, Raya Lucaria, Caelid", map_areas: &["m14", "m30_02", "m31_09", "m60_33-39_38-48", "m60_47-52_35-42"], damage_mult: 1.8_f32, rarity_weights: [30.0_f32, 35.0_f32, 25.0_f32, 8.0_f32, 2.0_f32], enemy_hp_hint: 400.0_f32 },
    RegionTiersRow { id: "t3", name: "Altus Plateau, Leyndell, Siofra, Ainsel", map_areas: &["m11", "m12_01", "m12_02", "m60_36-43_48-54"], damage_mult: 2.8_f32, rarity_weights: [15.0_f32, 30.0_f32, 35.0_f32, 15.0_f32, 5.0_f32], enemy_hp_hint: 800.0_f32 },
    RegionTiersRow { id: "t4", name: "Mountaintops, Consecrated Snowfield, Volcano Manor, Deeproot", map_areas: &["m16", "m12_03", "m60_47-54_50-58", "m60_44-46_55-58"], damage_mult: 4.0_f32, rarity_weights: [5.0_f32, 20.0_f32, 40.0_f32, 25.0_f32, 10.0_f32], enemy_hp_hint: 1500.0_f32 },
    RegionTiersRow { id: "t5", name: "Farum Azula, Haligtree, Leyndell Ashen, Mohgwyn", map_areas: &["m13", "m15", "m12_05", "m11_05", "m60_44-46_39-43"], damage_mult: 5.5_f32, rarity_weights: [0.0_f32, 10.0_f32, 35.0_f32, 35.0_f32, 20.0_f32], enemy_hp_hint: 2500.0_f32 },
    RegionTiersRow { id: "t6", name: "Land of Shadow (DLC)", map_areas: &["m20", "m21", "m22", "m25", "m28", "m61"], damage_mult: 7.0_f32, rarity_weights: [0.0_f32, 5.0_f32, 30.0_f32, 40.0_f32, 25.0_f32], enemy_hp_hint: 4000.0_f32 },
];

pub const SPAWN_RULES_CHEST_RULE: usize = 0;
pub const SPAWN_RULES_AMMO_RULE: usize = 1;

/// Where containers appear. Anchors are every Site of Grace in the game (BonfireWarpParam rows hold each grace's map tile and position), so placement covers the whole game, DLC included, without a hand-m
#[derive(Debug)]
pub struct SpawnRulesRow {
    /// key
    pub id: &'static str,
    /// what a container is placed next to: grace
    pub anchor: &'static str,
    /// containers per anchor
    pub count: u32,
    /// chance each one exists (deterministic per anchor+index)
    pub chance: f32,
    /// distance from the anchor
    pub offset_m: f32,
    /// no two containers closer than this
    pub min_spacing_m: f32,
    /// never | on_rest (resting at grace refills)
    pub respawn: &'static str,
}

pub static SPAWN_RULES: [SpawnRulesRow; 2] = [
    SpawnRulesRow { id: "chest_rule", anchor: "grace", count: 3, chance: 0.8_f32, offset_m: 14.0_f32, min_spacing_m: 10.0_f32, respawn: "never" },
    SpawnRulesRow { id: "ammo_rule", anchor: "grace", count: 2, chance: 0.6_f32, offset_m: 6.0_f32, min_spacing_m: 5.0_f32, respawn: "on_rest" },
];

pub const SYSTEMS_BOOT: usize = 0;
pub const SYSTEMS_SAFETY: usize = 1;
pub const SYSTEMS_SAVE_REDIRECT: usize = 2;
pub const SYSTEMS_ASSETS: usize = 3;
pub const SYSTEMS_INPUT: usize = 4;
pub const SYSTEMS_ER_UI_STATE: usize = 5;
pub const SYSTEMS_HIDE_ER_HUD: usize = 6;
pub const SYSTEMS_CAMERA: usize = 7;
pub const SYSTEMS_MOVEMENT: usize = 8;
pub const SYSTEMS_HEALTH_SHIELD: usize = 9;
pub const SYSTEMS_INVENTORY: usize = 10;
pub const SYSTEMS_GUNS: usize = 11;
pub const SYSTEMS_CONSUMABLES_USE: usize = 12;
pub const SYSTEMS_CONTAINERS: usize = 13;
pub const SYSTEMS_PICKUPS: usize = 14;
pub const SYSTEMS_HARVEST: usize = 15;
pub const SYSTEMS_BUILDING: usize = 16;
pub const SYSTEMS_RENDERER: usize = 17;
pub const SYSTEMS_PLAYER_MODEL: usize = 18;
pub const SYSTEMS_HUD: usize = 19;
pub const SYSTEMS_AUDIO: usize = 20;
pub const SYSTEMS_DEATH: usize = 21;
pub const SYSTEMS_LOG: usize = 22;

/// Every Elden Ring system the mashup touches, and how. One row = one hook/module in the DLL (fortring/src/systems/<id>.rs). er_api names the fromsoftware-rs type or the Windows API used.
#[derive(Debug)]
pub struct SystemsRow {
    /// key
    pub id: &'static str,
    /// what it does for the player
    pub what: &'static str,
    /// engine object / API it reads or writes
    pub er_api: &'static str,
    /// game task group or hook point
    pub when: &'static str,
    /// list of @systems rows
    pub depends: &'static [usize],
    /// sheets it reads
    pub sheets: &'static [&'static str],
    /// version
    pub release: &'static str,
}

pub static SYSTEMS: [SystemsRow; 23] = [
    SystemsRow { id: "boot", what: "waits until the game window and reflection singletons exist, then starts everything", er_api: "CSTaskImp::wait_for_instance, window visible", when: "DLL thread at load", depends: &[], sheets: &["none"], release: "0.1" },
    SystemsRow { id: "safety", what: "refuses to run unless launched offline through ModEngine2 (no EAC module in process)", er_api: "GetModuleHandleW(EasyAntiCheat), command line", when: "DllMain", depends: &[], sheets: &["none"], release: "0.1" },
    SystemsRow { id: "save_redirect", what: "keeps a separate save (ER0000.fnring.sl2) so the normal save never gets mod items", er_api: "CreateFileW hook on *.sl2 / *.sl2.bak", when: "DllMain (before the game opens saves)", depends: &[SYSTEMS_SAFETY], sheets: &["none"], release: "0.1" },
    SystemsRow { id: "assets", what: "loads the Fortnite cache made by the setup tool; shows a clear message if it is missing", er_api: "file IO in {localappdata}/FortniteRing/cache", when: "boot", depends: &[SYSTEMS_BOOT], sheets: &["fortnite_assets"], release: "0.1" },
    SystemsRow { id: "input", what: "reads keyboard/mouse, hides the mod's keys from Elden Ring, presses Elden Ring keys for passthrough actions", er_api: "IDirectInputDevice8::GetDeviceState hook", when: "game input poll", depends: &[SYSTEMS_BOOT], sheets: &["controls"], release: "0.1" },
    SystemsRow { id: "er_ui_state", what: "knows when an Elden Ring menu, map, dialogue or cutscene is open, and hands control back", er_api: "CSMenuManImp.ui_states, CSFeManImp", when: "every frame", depends: &[SYSTEMS_BOOT], sheets: &["none"], release: "0.1" },
    SystemsRow { id: "hide_er_hud", what: "hides Elden Ring's HP/FP/stamina bars and quick slots (menus stay)", er_api: "CSFeManImp HUD visibility flags", when: "every frame", depends: &[SYSTEMS_ER_UI_STATE], sheets: &["hud"], release: "0.1" },
    SystemsRow { id: "camera", what: "Fortnite over-the-shoulder camera with ADS", er_api: "CSCamera / ChrCam pers_cam matrix", when: "after game camera update", depends: &[SYSTEMS_INPUT, SYSTEMS_ER_UI_STATE], sheets: &["camera"], release: "0.1" },
    SystemsRow { id: "movement", what: "Fortnite movement controller (run, sprint, jump, crouch, fall damage); game gravity off while it drives", er_api: "CSChrPhysicsModule position/gravity_multiplier/gravity_disabled, CSHavokMan::cast_ray", when: "ChrIns_PostPhysics", depends: &[SYSTEMS_INPUT, SYSTEMS_CAMERA], sheets: &["movement"], release: "0.1" },
    SystemsRow { id: "health_shield", what: "Fortnite 100 HP + 100 shield: HP shown as % of Elden Ring HP; shield absorbs damage first", er_api: "ChrIns data module hp/max_hp, compare per tick", when: "ChrIns_PostPhysics", depends: &[SYSTEMS_BOOT], sheets: &["consumables"], release: "0.1" },
    SystemsRow { id: "inventory", what: "pickaxe + 5 weapon slots, ammo, materials, consumables; saved next to the Elden Ring save", er_api: "own JSON sidecar keyed by save slot", when: "on change / on Elden Ring save", depends: &[SYSTEMS_SAVE_REDIRECT], sheets: &["weapons", "ammo", "materials", "consumables"], release: "0.1" },
    SystemsRow { id: "guns", what: "fire, spread/bloom, recoil, reload, ADS; damage via real Elden Ring bullets so enemies react, die and drop runes", er_api: "CSBulletManager::spawn_bullet, a repurposed BulletParam + AtkParam_Pc row, SpEffect attack-rate row set per held gun", when: "ChrIns_PostPhysics", depends: &[SYSTEMS_INPUT, SYSTEMS_INVENTORY, SYSTEMS_CAMERA], sheets: &["weapons", "rarities", "region_tiers"], release: "0.1" },
    SystemsRow { id: "consumables_use", what: "use bandages/medkits/shield potions with Fortnite timings", er_api: "ChrIns hp write", when: "ChrIns_PostPhysics", depends: &[SYSTEMS_HEALTH_SHIELD, SYSTEMS_INVENTORY], sheets: &["consumables"], release: "0.1" },
    SystemsRow { id: "containers", what: "chests and ammo boxes across the map; E to search; loot pops out", er_api: "MsbRepository (anchors), CSActionButtonManImp prompt, own world-space draw", when: "ChrIns_PostPhysics", depends: &[SYSTEMS_INVENTORY, SYSTEMS_RENDERER], sheets: &["containers", "spawn_rules", "loot_tables", "region_tiers"], release: "0.1" },
    SystemsRow { id: "pickups", what: "dropped loot floats on the ground with rarity glow; E to pick up, swap if full", er_api: "own world-space draw", when: "ChrIns_PostPhysics", depends: &[SYSTEMS_INVENTORY, SYSTEMS_RENDERER], sheets: &["rarities"], release: "0.1" },
    SystemsRow { id: "harvest", what: "pickaxe swings ray-cast the world and give wood/stone/metal", er_api: "CSHavokMan::cast_ray hit asset name, CSWorldGeomMan", when: "ChrIns_PostPhysics", depends: &[SYSTEMS_INPUT, SYSTEMS_INVENTORY], sheets: &["harvestables", "materials"], release: "0.1" },
    SystemsRow { id: "building", what: "grid build preview, place wall/floor/ramp; HP builds up; you can stand on, climb and take cover behind them; your bullets, rockets and pickaxe damage them. (0.1: enemies pass through builds, see build_pieces.about)", er_api: "own oriented-box collision in world::ray, own mesh draw", when: "ChrIns_PostPhysics", depends: &[SYSTEMS_INPUT, SYSTEMS_INVENTORY, SYSTEMS_RENDERER], sheets: &["build_pieces", "materials"], release: "0.1" },
    SystemsRow { id: "renderer", what: "draws Fortnite meshes (outfit, guns, chests, builds, pickups) in the world with depth occlusion", er_api: "D3D12 hook via hudhook pre-ImGui pass, scene depth copy", when: "present", depends: &[SYSTEMS_ASSETS], sheets: &["fortnite_assets", "animations"], release: "0.1" },
    SystemsRow { id: "player_model", what: "hides the Tarnished and draws the Fortnite outfit with Fortnite animations at its position", er_api: "ChrIns model visibility flag, PlayerIns position/orientation", when: "present", depends: &[SYSTEMS_RENDERER, SYSTEMS_MOVEMENT], sheets: &["animations"], release: "0.1" },
    SystemsRow { id: "hud", what: "the Fortnite HUD", er_api: "ImGui via hudhook", when: "present", depends: &[SYSTEMS_ASSETS, SYSTEMS_ER_UI_STATE], sheets: &["hud"], release: "0.1" },
    SystemsRow { id: "audio", what: "plays Fortnite sounds (guns, chest hum, heals) with distance falloff", er_api: "XAudio2 (own voice, separate from Wwise)", when: "event", depends: &[SYSTEMS_ASSETS], sheets: &["fortnite_assets"], release: "0.1" },
    SystemsRow { id: "death", what: "on death: Fortnite-style eliminated screen, then Elden Ring's own respawn at grace; inventory kept", er_api: "FeTextEffectParam rows 5/50 blanked (no YOU DIED)", when: "on HP 0", depends: &[SYSTEMS_HEALTH_SHIELD], sheets: &["hud"], release: "0.1" },
    SystemsRow { id: "log", what: "writes FortniteRing.log for testing (boot, hits, chest rolls, harvest hits, build spawns)", er_api: "file", when: "always", depends: &[], sheets: &["none"], release: "0.1" },
];

pub const WEAPONS_AR: usize = 0;
pub const WEAPONS_PUMP: usize = 1;
pub const WEAPONS_SMG: usize = 2;
pub const WEAPONS_SNIPER: usize = 3;
pub const WEAPONS_PISTOL: usize = 4;
pub const WEAPONS_ROCKET: usize = 5;

/// One row per Fortnite gun. Damage is Fortnite's per-shot body damage by rarity [common, uncommon, rare, epic, legendary]; the DLL multiplies it by the region tier where the gun was found (region_tiers.
#[derive(Debug)]
pub struct WeaponsRow {
    /// stable key used by code and other sheets
    pub id: &'static str,
    /// display name on the HUD
    pub name: &'static str,
    /// fire behaviour family: rifle | shotgun | smg | sniper | pistol | launcher
    pub class: &'static str,
    /// @ammo row
    pub ammo: usize,
    /// body damage per shot (shotgun: whole shot) by rarity, 5 numbers
    pub damage: [f32; 5],
    /// headshot multiplier
    pub headshot_mult: f32,
    /// projectiles per shot
    pub pellets: u32,
    /// shots per second
    pub fire_rate: f32,
    /// true = hold to fire
    pub auto: bool,
    /// magazine size
    pub mag: u32,
    /// reload time in seconds by rarity, 5 numbers
    pub reload_s: [f32; 5],
    /// true = reloads one round at a time (pump)
    pub reload_per_shell: bool,
    /// max effective range in metres (bullet life)
    pub range_m: f32,
    /// distance where damage starts to drop
    pub falloff_start_m: f32,
    /// damage fraction at range_m
    pub falloff_min: f32,
    /// cone half-angle hip fire
    pub spread_hip_deg: f32,
    /// cone half-angle aiming down sights
    pub spread_ads_deg: f32,
    /// spread added per shot
    pub bloom_per_shot_deg: f32,
    /// camera kick per shot
    pub recoil_pitch_deg: f32,
    /// projectile speed (hitscan guns use a fast engine bullet)
    pub bullet_speed_mps: f32,
    /// 0 = no splash
    pub explosion_radius_m: f32,
    /// multiplier against player builds
    pub build_damage_mult: f32,
    /// camera FOV while aiming
    pub ads_fov: f32,
    /// which rarities can drop: list of @rarities ids
    pub rarities: &'static [usize],
    /// @fortnite_assets row for the weapon mesh
    pub fn_mesh: usize,
    /// @fortnite_assets row for the HUD icon
    pub fn_icon: usize,
    /// @fortnite_assets row
    pub fn_fire_sound: usize,
    /// @fortnite_assets row
    pub fn_reload_sound: usize,
    /// @animations group for fire/reload
    pub anim_set: usize,
}

pub static WEAPONS: [WeaponsRow; 6] = [
    WeaponsRow { id: "ar", name: "Assault Rifle", class: "rifle", ammo: AMMO_MEDIUM, damage: [30.0_f32, 31.0_f32, 33.0_f32, 35.0_f32, 36.0_f32], headshot_mult: 1.5_f32, pellets: 1, fire_rate: 5.5_f32, auto: true, mag: 30, reload_s: [2.7_f32, 2.6_f32, 2.5_f32, 2.4_f32, 2.3_f32], reload_per_shell: false, range_m: 250.0_f32, falloff_start_m: 50.0_f32, falloff_min: 0.6_f32, spread_hip_deg: 2.4_f32, spread_ads_deg: 0.6_f32, bloom_per_shot_deg: 0.35_f32, recoil_pitch_deg: 0.6_f32, bullet_speed_mps: 900.0_f32, explosion_radius_m: 0.0_f32, build_damage_mult: 1.0_f32, ads_fov: 60.0_f32, rarities: &[RARITIES_COMMON, RARITIES_UNCOMMON, RARITIES_RARE, RARITIES_EPIC, RARITIES_LEGENDARY], fn_mesh: FORTNITE_ASSETS_MESH_AR, fn_icon: FORTNITE_ASSETS_ICON_AR, fn_fire_sound: FORTNITE_ASSETS_SND_AR_FIRE, fn_reload_sound: FORTNITE_ASSETS_SND_AR_RELOAD, anim_set: ANIMATIONS_RIFLE },
    WeaponsRow { id: "pump", name: "Pump Shotgun", class: "shotgun", ammo: AMMO_SHELLS, damage: [85.0_f32, 90.0_f32, 95.0_f32, 100.0_f32, 105.0_f32], headshot_mult: 2.0_f32, pellets: 10, fire_rate: 0.7_f32, auto: false, mag: 5, reload_s: [5.1_f32, 4.8_f32, 4.6_f32, 4.4_f32, 4.2_f32], reload_per_shell: true, range_m: 30.0_f32, falloff_start_m: 6.0_f32, falloff_min: 0.2_f32, spread_hip_deg: 5.0_f32, spread_ads_deg: 4.0_f32, bloom_per_shot_deg: 0.0_f32, recoil_pitch_deg: 3.0_f32, bullet_speed_mps: 600.0_f32, explosion_radius_m: 0.0_f32, build_damage_mult: 1.0_f32, ads_fov: 70.0_f32, rarities: &[RARITIES_COMMON, RARITIES_UNCOMMON, RARITIES_RARE, RARITIES_EPIC, RARITIES_LEGENDARY], fn_mesh: FORTNITE_ASSETS_MESH_PUMP, fn_icon: FORTNITE_ASSETS_ICON_PUMP, fn_fire_sound: FORTNITE_ASSETS_SND_PUMP_FIRE, fn_reload_sound: FORTNITE_ASSETS_SND_PUMP_RELOAD, anim_set: ANIMATIONS_SHOTGUN },
    WeaponsRow { id: "smg", name: "Submachine Gun", class: "smg", ammo: AMMO_LIGHT, damage: [17.0_f32, 18.0_f32, 19.0_f32, 20.0_f32, 21.0_f32], headshot_mult: 1.75_f32, pellets: 1, fire_rate: 12.0_f32, auto: true, mag: 30, reload_s: [2.2_f32, 2.1_f32, 2.0_f32, 1.9_f32, 1.8_f32], reload_per_shell: false, range_m: 120.0_f32, falloff_start_m: 25.0_f32, falloff_min: 0.5_f32, spread_hip_deg: 3.0_f32, spread_ads_deg: 1.5_f32, bloom_per_shot_deg: 0.25_f32, recoil_pitch_deg: 0.4_f32, bullet_speed_mps: 700.0_f32, explosion_radius_m: 0.0_f32, build_damage_mult: 1.0_f32, ads_fov: 65.0_f32, rarities: &[RARITIES_COMMON, RARITIES_UNCOMMON, RARITIES_RARE, RARITIES_EPIC, RARITIES_LEGENDARY], fn_mesh: FORTNITE_ASSETS_MESH_SMG, fn_icon: FORTNITE_ASSETS_ICON_SMG, fn_fire_sound: FORTNITE_ASSETS_SND_SMG_FIRE, fn_reload_sound: FORTNITE_ASSETS_SND_SMG_RELOAD, anim_set: ANIMATIONS_RIFLE },
    WeaponsRow { id: "sniper", name: "Bolt-Action Sniper Rifle", class: "sniper", ammo: AMMO_HEAVY, damage: [95.0_f32, 100.0_f32, 105.0_f32, 110.0_f32, 116.0_f32], headshot_mult: 2.5_f32, pellets: 1, fire_rate: 0.33_f32, auto: false, mag: 1, reload_s: [3.3_f32, 3.2_f32, 3.0_f32, 2.85_f32, 2.7_f32], reload_per_shell: false, range_m: 600.0_f32, falloff_start_m: 600.0_f32, falloff_min: 1.0_f32, spread_hip_deg: 6.0_f32, spread_ads_deg: 0.0_f32, bloom_per_shot_deg: 0.0_f32, recoil_pitch_deg: 4.0_f32, bullet_speed_mps: 450.0_f32, explosion_radius_m: 0.0_f32, build_damage_mult: 1.0_f32, ads_fov: 25.0_f32, rarities: &[RARITIES_COMMON, RARITIES_UNCOMMON, RARITIES_RARE, RARITIES_EPIC, RARITIES_LEGENDARY], fn_mesh: FORTNITE_ASSETS_MESH_SNIPER, fn_icon: FORTNITE_ASSETS_ICON_SNIPER, fn_fire_sound: FORTNITE_ASSETS_SND_SNIPER_FIRE, fn_reload_sound: FORTNITE_ASSETS_SND_SNIPER_RELOAD, anim_set: ANIMATIONS_RIFLE },
    WeaponsRow { id: "pistol", name: "Pistol", class: "pistol", ammo: AMMO_LIGHT, damage: [24.0_f32, 25.0_f32, 26.0_f32, 27.0_f32, 28.0_f32], headshot_mult: 2.0_f32, pellets: 1, fire_rate: 6.75_f32, auto: false, mag: 16, reload_s: [1.5_f32, 1.45_f32, 1.4_f32, 1.35_f32, 1.3_f32], reload_per_shell: false, range_m: 100.0_f32, falloff_start_m: 20.0_f32, falloff_min: 0.5_f32, spread_hip_deg: 2.0_f32, spread_ads_deg: 0.8_f32, bloom_per_shot_deg: 0.4_f32, recoil_pitch_deg: 0.8_f32, bullet_speed_mps: 700.0_f32, explosion_radius_m: 0.0_f32, build_damage_mult: 1.0_f32, ads_fov: 70.0_f32, rarities: &[RARITIES_COMMON, RARITIES_UNCOMMON, RARITIES_RARE, RARITIES_EPIC, RARITIES_LEGENDARY], fn_mesh: FORTNITE_ASSETS_MESH_PISTOL, fn_icon: FORTNITE_ASSETS_ICON_PISTOL, fn_fire_sound: FORTNITE_ASSETS_SND_PISTOL_FIRE, fn_reload_sound: FORTNITE_ASSETS_SND_PISTOL_RELOAD, anim_set: ANIMATIONS_PISTOL },
    WeaponsRow { id: "rocket", name: "Rocket Launcher", class: "launcher", ammo: AMMO_ROCKETS, damage: [100.0_f32, 105.0_f32, 110.0_f32, 116.0_f32, 121.0_f32], headshot_mult: 1.0_f32, pellets: 1, fire_rate: 0.75_f32, auto: false, mag: 1, reload_s: [3.6_f32, 3.4_f32, 3.2_f32, 3.0_f32, 2.8_f32], reload_per_shell: false, range_m: 200.0_f32, falloff_start_m: 200.0_f32, falloff_min: 1.0_f32, spread_hip_deg: 0.5_f32, spread_ads_deg: 0.0_f32, bloom_per_shot_deg: 0.0_f32, recoil_pitch_deg: 2.5_f32, bullet_speed_mps: 45.0_f32, explosion_radius_m: 3.5_f32, build_damage_mult: 4.0_f32, ads_fov: 60.0_f32, rarities: &[RARITIES_COMMON, RARITIES_UNCOMMON, RARITIES_RARE, RARITIES_EPIC, RARITIES_LEGENDARY], fn_mesh: FORTNITE_ASSETS_MESH_ROCKET, fn_icon: FORTNITE_ASSETS_ICON_ROCKET, fn_fire_sound: FORTNITE_ASSETS_SND_ROCKET_FIRE, fn_reload_sound: FORTNITE_ASSETS_SND_ROCKET_RELOAD, anim_set: ANIMATIONS_LAUNCHER },
];
