#!/usr/bin/env python3
"""Generate code from the sheets: one Rust struct per sheet, one static entry per row.

  fortring/src/generated.rs      (the Elden Ring DLL)
  extractor/Generated.cs         (the Fortnite setup tool: the asset list)

References (@sheet:id) become indices into that sheet's array, with a named
constant per row (WEAPONS_AR, AMMO_MEDIUM, ...). Sheets whose columns are
id/value/... (movement, camera) become plain constants.
Run tools/preflight.py first; this script refuses to run when it fails.
"""
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SHEETS = ROOT / "sheets"
REF = re.compile(r"^@([a-z_]+):([a-z0-9_]+)$")
INT_LIST_COLS = {"candidates"}
INT_COLS = {"count", "pellets", "mag", "index", "max", "chest_drop", "box_drop", "stack", "piece_cost", "rolls",
            "per_hit", "crit_per_hit", "hits_to_break", "wall_hp", "floor_hp", "ramp_hp"}


def camel(s):
    return "".join(p.capitalize() for p in s.split("_"))


def const(sheet, rid):
    return f"{sheet.upper()}_{rid.upper()}"


class Gen:
    def __init__(self, sheets):
        self.sheets = sheets
        self.index = {n: {r["id"]: i for i, r in enumerate(d["rows"])} for n, d in sheets.items()}
        self.ref_sheets = sorted(sheets)

    def ref(self, s):
        m = REF.match(s)
        return f"{const(m.group(1), m.group(2))}" if m else None

    def rtype(self, col, v):
        if isinstance(v, bool):
            return "bool"
        if isinstance(v, int) and col in INT_COLS:
            return "u32"
        if isinstance(v, (int, float)):
            return "f32"
        if isinstance(v, str):
            return "usize" if REF.match(v) else "&'static str"
        if isinstance(v, list):
            if v and all(isinstance(x, list) for x in v):
                return "&'static [(Ref, f32, u32)]"
            if v and all(isinstance(x, (int, float)) and not isinstance(x, bool) for x in v):
                return f"[f32; {len(v)}]"
            if all(isinstance(x, str) and REF.match(x) for x in v):
                return "&'static [usize]"
            return "&'static [&'static str]"
        if isinstance(v, dict):
            return "&'static [(&'static str, usize)]"
        raise TypeError(f"{col}: {v!r}")

    def col_type(self, col, values):
        """Column-wide type: refs with some "none" become Option<usize>; ref lists drop "none"."""
        def isref(x):
            return isinstance(x, str) and REF.match(x)
        if all(isinstance(v, str) and (isref(v) or v == "none") for v in values) and any(isref(v) for v in values):
            return "Option<usize>" if "none" in values else "usize"
        if all(isinstance(v, list) and all(isinstance(x, str) and (isref(x) or x == "none") for x in v) for v in values) \
                and any(isref(x) for v in values for x in v):
            return "&'static [usize]"
        if col in INT_LIST_COLS:
            return "&'static [u32]"
        nums = [v for v in values if isinstance(v, list) and v and all(isinstance(x, (int, float)) and not isinstance(x, bool) for x in v)]
        if nums and len(nums) == len(values) and len({len(v) for v in nums}) > 1:
            return "&'static [f32]"
        return self.rtype(col, next((v for v in values if v not in ([], "none", ["none"])), values[0]))

    def rval(self, ty, v):
        if ty == "Option<usize>":
            return "None" if v == "none" else f"Some({self.ref(v)})"
        if ty == "bool":
            return "true" if v else "false"
        if ty == "u32":
            return str(int(v))
        if ty == "f32":
            return f"{float(v)!r}_f32"
        if ty == "usize":
            return self.ref(v)
        if ty == "&'static str":
            return json.dumps(v)
        if ty == "&'static [u32]":
            return "&[" + ", ".join(str(int(x)) for x in v) + "]"
        if ty == "&'static [f32]":
            return "&[" + ", ".join(f"{float(x)!r}_f32" for x in v) + "]"
        if ty.startswith("[f32"):
            return "[" + ", ".join(f"{float(x)!r}_f32" for x in v) + "]"
        if ty == "&'static [usize]":
            return "&[" + ", ".join(self.ref(x) for x in v if x != "none") + "]"
        if ty == "&'static [&'static str]":
            return "&[" + ", ".join(json.dumps(x) for x in v) + "]"
        if ty.startswith("&'static [(Ref"):
            out = []
            for r, w, n in v:
                m = REF.match(r)
                out.append(f"(Ref::{camel(m.group(1))}({const(m.group(1), m.group(2))}), {float(w)!r}_f32, {int(n)})")
            return "&[" + ", ".join(out) + "]"
        if ty.startswith("&'static [(&"):
            return "&[" + ", ".join(f"({json.dumps(k)}, {self.ref(x)})" for k, x in v.items()) + "]"
        raise TypeError(ty)

    def rust(self):
        o = ["// GENERATED by tools/codegen.py from sheets/*.json. Do not edit: change the sheet and regenerate.",
             "#![allow(dead_code, clippy::all)]", ""]
        o.append("/// A reference to a row in another sheet (loot table entries).")
        o.append("#[derive(Clone, Copy, Debug, PartialEq, Eq, serde::Serialize, serde::Deserialize)]")
        o.append("pub enum Ref {")
        for n in self.ref_sheets:
            o.append(f"    {camel(n)}(usize),")
        o.append("}\n")
        for name, d in self.sheets.items():
            for i, r in enumerate(d["rows"]):
                o.append(f"pub const {const(name, r['id'])}: usize = {i};")
            o.append("")
            cols = list(d["columns"])
            if cols[:2] == ["id", "value"]:
                o.append(f"// {name}: {d['about'][:110]}")
                for r in d["rows"]:
                    ty = self.rtype("value", r["value"])
                    o.append(f"/// {r.get('what', '')} ({r.get('unit', '')})".rstrip(" ()"))
                    o.append(f"pub const {name.upper()}_{r['id'].upper()}_V: {ty} = {self.rval(ty, r['value'])};")
                o.append("")
                continue
            sname = camel(name) + "Row"
            types = {c: self.col_type(c, [r[c] for r in d["rows"]]) for c in cols}
            o.append(f"/// {d['about'][:200]}")
            o.append("#[derive(Debug)]")
            o.append(f"pub struct {sname} {{")
            for c in cols:
                o.append(f"    /// {d['columns'][c]}")
                o.append(f"    pub {c}: {types[c]},")
            o.append("}\n")
            o.append(f"pub static {name.upper()}: [{sname}; {len(d['rows'])}] = [")
            for r in d["rows"]:
                fields = ", ".join(f"{c}: {self.rval(types[c], r[c])}" for c in cols)
                o.append(f"    {sname} {{ {fields} }},")
            o.append("];\n")
        return "\n".join(o)

    def csharp(self):
        d = self.sheets["fortnite_assets"]
        o = ["// GENERATED by tools/codegen.py from sheets/fortnite_assets.json. Do not edit.",
             "namespace FortniteRing.Setup;", "",
             "public sealed record AssetRow(string Id, string Kind, string Query, string Out, bool Required);", "",
             "public static class Sheet", "{", "    public static readonly AssetRow[] Assets =", "    ["]
        for r in d["rows"]:
            o.append(f"        new({json.dumps(r['id'])}, {json.dumps(r['kind'])}, {json.dumps(r['query'])}, "
                     f"{json.dumps(r['out'])}, {'true' if r['required'] else 'false'}),")
        o += ["    ];", "}", ""]
        return "\n".join(o)


def main():
    if subprocess.run([sys.executable, str(ROOT / "tools/preflight.py")], capture_output=True).returncode:
        raise SystemExit("preflight failed: run tools/preflight.py and fix the sheets first")
    sheets = {p.stem: json.loads(p.read_text()) for p in sorted(SHEETS.glob("*.json"))}
    g = Gen(sheets)
    targets = {ROOT / "fortring/src/generated.rs": g.rust(), ROOT / "extractor/Generated.cs": g.csharp()}
    for path, text in targets.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
        print(f"wrote {path.relative_to(ROOT)} ({len(text.splitlines())} lines)")


if __name__ == "__main__":
    main()
